clear;
close all;
clc;

%% ============================================================
% ADVANCED HILBERT-AMPLITUDE FIGURE
%
% Observed spectrum:
% Lomb-Scargle PSD of the original, unsmoothed Hilbert amplitude.
%
% Null model:
% Monte Carlo AR(1) red-noise innovation bootstrap fitted directly
% to the mean-centred Hilbert-amplitude series. The 100 kyr smooth
% is plotted for visual reference only and is not used in the
% spectral significance calculation.
%% ============================================================

%% 1. LOAD RESULTS FROM Main_Datat.m

results_file = "Main_Data_results.mat";

if ~isfile(results_file)

    error("Main_Datat_results.mat was not found. Run Main_Datat.m first.");

end


S = load(results_file);


required_variables = [
    "R"
    "opts"
    "plot_opts"
    "mis_intervals"
];


for k = 1:numel(required_variables)

    variable_name = char(required_variables(k));

    if ~isfield(S, variable_name)

        error( ...
            "Variable '%s' is missing from %s.", ...
            variable_name, ...
            results_file);

    end

end


R = S.R;

opts = S.opts;

plot_opts = S.plot_opts;

mis_intervals = S.mis_intervals;


fprintf("\nMain-pipeline results loaded successfully.\n");


%% ============================================================
% 2. LOMB-SCARGLE AND BOOTSTRAP SETTINGS
%% ============================================================


opts.spec.fmin = 0.008;              % cycles kyr^-1


opts.spec.fmax = 0.12;               % cycles kyr^-1


opts.spec.oversample_factor = 3;     % frequency-grid oversampling


opts.spec.nboot = 100;                 % final analysis


opts.spec.alpha = 0.05;              % pointwise 95% threshold


opts.spec.seed = 20260709;           % reproducible bootstrap



%% ============================================================
% 3. CALCULATE SPECTRA
%% ============================================================


R = calculate_hilbert_lomb_spectra( ...
    R, ...
    opts);



%% ============================================================
% 4. CREATE FIGURE
%% ============================================================


fig = plot_hilbert_and_lomb_spectra( ...
    R, ...
    mis_intervals, ...
    opts, ...
    plot_opts);



%% ============================================================
% 5. SAVE RESULTS
%% ============================================================


save( ...
    "Hilbert_LombScargle_results.mat", ...
    "R", ...
    "opts", ...
    "-v7.3");


fprintf( ...
    "\nSpectral results saved as Hilbert_LombScargle_results.mat.\n");


fprintf( ...
    "Advanced Hilbert-amplitude figure created successfully.\n\n");



%% ============================================================
% FUNCTION:
% CALCULATE SPECTRA FOR ALL RECORDS
%% ============================================================

function R = calculate_hilbert_lomb_spectra( ...
    R, ...
    opts)


    rng( ...
        opts.spec.seed, ...
        "twister");


    number_of_records = ...
        numel(R);


    fprintf( ...
        "\nCalculating Lomb-Scargle spectra...\n");


    for i = 1:number_of_records


        %% ----------------------------------------------------
        % LOAD DATA
        %% ----------------------------------------------------


        age = ...
            R(i).age_hilbert(:);


        hilbert_amplitude = ...
            R(i).hilbert_amp_z(:);


        long_term_trend = ...
            R(i).hilbert_amp_z_smooth(:);


        edge_keep = ...
            logical( ...
            R(i).plot_edge_keep(:));


        valid = ...
            edge_keep & ...
            isfinite(age) & ...
            isfinite(hilbert_amplitude) & ...
            isfinite(long_term_trend);


        age = ...
            age(valid);


        hilbert_amplitude = ...
            hilbert_amplitude(valid);


        long_term_trend = ...
            long_term_trend(valid);


        if numel(age) < 100

            error( ...
                "%s contains too few valid values.", ...
                R(i).label);

        end



        %% ----------------------------------------------------
        % SORT BY AGE
        %% ----------------------------------------------------


        [age, sort_index] = ...
            sort(age);


        hilbert_amplitude = ...
            hilbert_amplitude(sort_index);


        long_term_trend = ...
            long_term_trend(sort_index);



        %% ----------------------------------------------------
        % FREQUENCY LIMITS
        %% ----------------------------------------------------


        median_timestep = ...
            median( ...
            diff(age));


        nyquist_frequency = ...
            1 / ...
            (2 * median_timestep);


        minimum_frequency = ...
            opts.spec.fmin;


        maximum_frequency = ...
            min( ...
            opts.spec.fmax, ...
            0.98 * nyquist_frequency);


        if maximum_frequency <= minimum_frequency

            error( ...
                "Invalid frequency range for %s.", ...
                R(i).label);

        end



        %% ----------------------------------------------------
        % FREQUENCY GRID
        %
        % The nominal Rayleigh frequency resolution is:
        %
        % df = 1 / record span
        %
        % Oversampling improves the visual continuity of the
        % spectrum but does not increase its intrinsic spectral
        % resolution.
        %% ----------------------------------------------------


        record_span = ...
            max(age) - ...
            min(age);


        if record_span <= 0

            error( ...
                "Invalid record span for %s.", ...
                R(i).label);

        end


        df_natural = ...
            1 / record_span;


        df_grid = ...
            df_natural / ...
            opts.spec.oversample_factor;


        frequency_grid = ...
            ( ...
            minimum_frequency: ...
            df_grid: ...
            maximum_frequency ...
            )';


        if numel(frequency_grid) < 10

            frequency_grid = ...
                linspace( ...
                minimum_frequency, ...
                maximum_frequency, ...
                10)';

        end



        %% ----------------------------------------------------
        % OBSERVED LOMB-SCARGLE SPECTRUM
        %
        % The original, unsmoothed Hilbert amplitude is used.
        %
        % Only the constant mean is removed.
        %
        % No long-term trend is subtracted.
        %% ----------------------------------------------------


        observed_record = ...
            hilbert_amplitude - ...
            mean(hilbert_amplitude);


        observed_power = ...
            plomb( ...
            observed_record, ...
            age, ...
            frequency_grid, ...
            "psd");


        observed_power = ...
            observed_power(:);



        %% ----------------------------------------------------
        % FIT AR(1) DIRECTLY TO THE SAME MEAN-CENTRED SERIES
        %% ----------------------------------------------------


        series_previous = ...
            observed_record(1:end-1);


        series_next = ...
            observed_record(2:end);


        denominator = ...
            sum( ...
            series_previous .^ 2);


        if denominator == 0


            phi = 0;


        else


            phi = ...
                sum( ...
                series_previous .* ...
                series_next) / ...
                denominator;


        end



        %% ----------------------------------------------------
        % NUMERICAL PROTECTION
        %% ----------------------------------------------------


        phi = ...
            max( ...
            min( ...
            phi, ...
            0.995), ...
            -0.995);



        %% ----------------------------------------------------
        % AR(1) INNOVATIONS
        %% ----------------------------------------------------


        innovations = ...
            series_next - ...
            phi .* ...
            series_previous;


        innovations = ...
            innovations - ...
            mean(innovations);


        innovation_standard_deviation = ...
            std( ...
            innovations, ...
            0);


        if ...
                ~isfinite(innovation_standard_deviation) || ...
                innovation_standard_deviation == 0


            error( ...
                "%s has invalid AR(1) innovation variance.", ...
                R(i).label);


        end



        %% ----------------------------------------------------
        % BOOTSTRAP SETUP
        %% ----------------------------------------------------


        number_of_bootstraps = ...
            opts.spec.nboot;


        number_of_frequencies = ...
            numel(frequency_grid);


        number_of_innovations = ...
            numel(innovations);


        number_of_points = ...
            numel(age);


        bootstrap_spectra = ...
            zeros( ...
            number_of_frequencies, ...
            number_of_bootstraps, ...
            "single");



        %% ----------------------------------------------------
        % BURN-IN
        %
        % The burn-in reduces dependence on the initial value.
        %% ----------------------------------------------------


        burn_in = ...
            max( ...
            500, ...
            ceil( ...
            10 / ...
            max( ...
            1 - abs(phi), ...
            1e-3)));



        %% ----------------------------------------------------
        % AR(1) INNOVATION BOOTSTRAP
        %% ----------------------------------------------------


        fprintf( ...
            "  %s: phi = %.3f | %d bootstrap simulations\n", ...
            R(i).label, ...
            phi, ...
            number_of_bootstraps);


        for bootstrap_number = 1:number_of_bootstraps


            %% -----------------------------------------------
            % RESAMPLE INNOVATIONS WITH REPLACEMENT
            %% -----------------------------------------------


            random_indices = ...
                randi( ...
                number_of_innovations, ...
                number_of_points + burn_in, ...
                1);


            bootstrap_innovations = ...
                innovations(random_indices);



            %% -----------------------------------------------
            % GENERATE AR(1) SURROGATE
            %% -----------------------------------------------


            bootstrap_series_full = ...
                filter( ...
                1, ...
                [1 -phi], ...
                bootstrap_innovations);



            %% -----------------------------------------------
            % REMOVE BURN-IN
            %% -----------------------------------------------


            bootstrap_series = ...
                bootstrap_series_full( ...
                burn_in + 1:end);



            %% -----------------------------------------------
            % MEAN-CENTRE SURROGATE
            %% -----------------------------------------------


            bootstrap_series = ...
                bootstrap_series - ...
                mean(bootstrap_series);



            %% -----------------------------------------------
            % APPLY THE SAME LOMB-SCARGLE CALCULATION
            %% -----------------------------------------------


            bootstrap_power = ...
                plomb( ...
                bootstrap_series, ...
                age, ...
                frequency_grid, ...
                "psd");


            bootstrap_spectra( ...
                :, ...
                bootstrap_number) = ...
                single( ...
                bootstrap_power(:));


        end



        %% ----------------------------------------------------
        % FREQUENCY-WISE POINTWISE 95% THRESHOLD
        %% ----------------------------------------------------


        significance_percentile = ...
            100 * ...
            (1 - opts.spec.alpha);


        significance_95 = ...
            double( ...
            prctile( ...
            bootstrap_spectra, ...
            significance_percentile, ...
            2));



        %% ----------------------------------------------------
        % SAVE RESULTS
        %% ----------------------------------------------------


        R(i).spec_frequency = ...
            frequency_grid;


        R(i).spec_power = ...
            observed_power;


        R(i).spec_sig95 = ...
            significance_95;


        R(i).spec_ar1 = ...
            phi;


        % Saved for reference only.
        %
        % The long-term trend is not used in the spectral
        % calculation or in the AR(1) bootstrap.

        R(i).spec_long_term_trend = ...
            long_term_trend;


    end


    fprintf( ...
        "All Lomb-Scargle calculations completed.\n");


end



%% ============================================================
% FUNCTION:
% COMBINED HILBERT-AMPLITUDE AND SPECTRUM FIGURE
%% ============================================================

function fig = plot_hilbert_and_lomb_spectra( ...
    R, ...
    mis_intervals, ...
    opts, ...
    plot_opts)


    number_of_records = ...
        numel(R);



    %% --------------------------------------------------------
    % FIGURE
    %% --------------------------------------------------------


    fig = ...
        figure( ...
        "Color", ...
        "w", ...
        "Position", ...
        [50 40 1250 760]);



    %% --------------------------------------------------------
    % MANUAL LAYOUT
    %% --------------------------------------------------------


    left_margin = ...
        0.065;


    top_margin = ...
        0.080;


    bottom_margin = ...
        0.055;


    % White separator between every panel row
    row_gap = ...
        0.002;


    column_gap = ...
        0.040;


    time_width = ...
        0.640;


    spectrum_left = ...
        left_margin + ...
        time_width + ...
        column_gap;


    spectrum_width = ...
        0.170;


    axis_height = ...
        ( ...
        1 - ...
        top_margin - ...
        bottom_margin - ...
        (number_of_records - 1) * ...
        row_gap ...
        ) / ...
        number_of_records;



    %% --------------------------------------------------------
    % AXIS STORAGE
    %% --------------------------------------------------------


    time_axes = ...
        gobjects( ...
        number_of_records, ...
        1);


    spectrum_axes = ...
        gobjects( ...
        number_of_records, ...
        1);



    %% --------------------------------------------------------
    % COLOURS
    %% --------------------------------------------------------


    spectrum_colour = ...
        [0.05 0.05 0.05];


    significance_colour = ...
        [0.85 0.10 0.10];


    % Very pale pink background for the spectrum panels
    spectrum_background_colour = ...
        [0.985 0.955 0.965];



    %% --------------------------------------------------------
    % ORBITAL PERIODS
    %% --------------------------------------------------------


    orbital_periods = ...
        [101 41 23 19];


    orbital_frequencies = ...
        1 ./ ...
        orbital_periods;


    orbital_colours = [
        0.82 0.15 0.20
        0.95 0.40 0.05
        0.95 0.63 0.05
        0.95 0.63 0.05
    ];



    %% ========================================================
    % LOOP THROUGH RECORDS
    %% ========================================================


    for i = 1:number_of_records


        y_position = ...
            1 - ...
            top_margin - ...
            i * ...
            axis_height - ...
            (i - 1) * ...
            row_gap;



        %% ====================================================
        % LEFT:
        % HILBERT AMPLITUDE
        %% ====================================================


        time_axes(i) = ...
            axes( ...
            "Parent", ...
            fig, ...
            "Position", ...
            [ ...
            left_margin ...
            y_position ...
            time_width ...
            axis_height ...
            ]);


        hold( ...
            time_axes(i), ...
            "on");



        %% ----------------------------------------------------
        % LOAD PLOTTING DATA
        %% ----------------------------------------------------


        plotting_indices = ...
            logical( ...
            R(i).plot_edge_keep(:));


        age = ...
            R(i).age_hilbert( ...
            plotting_indices);


        hilbert_amplitude = ...
            R(i).hilbert_amp_z( ...
            plotting_indices);


        long_term_trend = ...
            R(i).hilbert_amp_z_smooth( ...
            plotting_indices);



        %% ----------------------------------------------------
        % LEFT AXIS LIMITS AND STYLE
        %% ----------------------------------------------------


        xlim( ...
            time_axes(i), ...
            [ ...
            opts.age_min ...
            opts.age_max ...
            ]);


        combined_y = [
            hilbert_amplitude(:)
            long_term_trend(:)
        ];


        set_nice_ylim_local( ...
            time_axes(i), ...
            combined_y);


        style_axis_local( ...
            time_axes(i), ...
            plot_opts);


        format_y_axis_local( ...
            time_axes(i), ...
            plot_opts.n_yticks);



        %% ----------------------------------------------------
        % BACKGROUND LAYERS
        %% ----------------------------------------------------


        add_mis_shading_local( ...
            time_axes(i), ...
            mis_intervals, ...
            plot_opts);


        add_custom_grid_local( ...
            time_axes(i), ...
            opts, ...
            plot_opts);


        add_hiatus_markers_local( ...
            time_axes(i), ...
            R(i), ...
            plot_opts);



        %% ----------------------------------------------------
        % HILBERT AMPLITUDE
        %% ----------------------------------------------------


        hilbert_line = ...
            plot( ...
            time_axes(i), ...
            age, ...
            hilbert_amplitude, ...
            "Color", ...
            plot_opts.hilbert_col, ...
            "LineWidth", ...
            plot_opts.hilbert_line_width);



        %% ----------------------------------------------------
        % 100 KYR GAUSSIAN SMOOTH
        %% ----------------------------------------------------


        trend_line = ...
            plot( ...
            time_axes(i), ...
            age, ...
            long_term_trend, ...
            "Color", ...
            plot_opts.trend_col, ...
            "LineWidth", ...
            plot_opts.trend_line_width);



        %% ----------------------------------------------------
        % LEGEND AND MIS LABELS
        %% ----------------------------------------------------


        if i == 1


            legend( ...
                time_axes(i), ...
                [ ...
                hilbert_line ...
                trend_line ...
                ], ...
                { ...
                "Hilbert amplitude", ...
                "100 kyr Gaussian smooth" ...
                }, ...
                "Location", ...
                "northeast", ...
                "Box", ...
                "off", ...
                "FontSize", ...
                plot_opts.legend_font_size, ...
                "FontName", ...
                plot_opts.font_name);


            add_mis_labels_local( ...
                time_axes(i), ...
                mis_intervals, ...
                plot_opts);


        end



        %% ----------------------------------------------------
        % RECORD LABEL
        %% ----------------------------------------------------


        ylabel( ...
            time_axes(i), ...
            R(i).label, ...
            "Interpreter", ...
            "none", ...
            "FontSize", ...
            plot_opts.ylabel_font_size, ...
            "FontWeight", ...
            "bold", ...
            "FontName", ...
            plot_opts.font_name);



        %% ----------------------------------------------------
        % PANEL LABEL
        %% ----------------------------------------------------


        add_panel_label_local( ...
            time_axes(i), ...
            i, ...
            plot_opts);



        %% ----------------------------------------------------
        % AGE AXIS
        %% ----------------------------------------------------


        if i == 1


            time_axes(i).XAxisLocation = ...
                "top";


            xlabel( ...
                time_axes(i), ...
                "Age BP (kyr)", ...
                "FontSize", ...
                plot_opts.xlabel_font_size, ...
                "FontWeight", ...
                "bold", ...
                "FontName", ...
                plot_opts.font_name);


        elseif i == number_of_records


            time_axes(i).XAxisLocation = ...
                "bottom";


            xlabel( ...
                time_axes(i), ...
                "Age BP (kyr)", ...
                "FontSize", ...
                plot_opts.xlabel_font_size, ...
                "FontWeight", ...
                "bold", ...
                "FontName", ...
                plot_opts.font_name);


        else


            % Hide the complete interior x-axis so that the
            % white separator remains visible between panels.
            time_axes(i).XAxis.Visible = ...
                "off";


        end



        %% ====================================================
        % RIGHT:
        % LOMB-SCARGLE SPECTRUM
        %% ====================================================


        spectrum_axes(i) = ...
            axes( ...
            "Parent", ...
            fig, ...
            "Position", ...
            [ ...
            spectrum_left ...
            y_position ...
            spectrum_width ...
            axis_height ...
            ]);


        hold( ...
            spectrum_axes(i), ...
            "on");



        %% ----------------------------------------------------
        % SPECTRUM AXIS STYLE
        %% ----------------------------------------------------


        style_axis_local( ...
            spectrum_axes(i), ...
            plot_opts);


        set( ...
            spectrum_axes(i), ...
            "Color", ...
            spectrum_background_colour, ...
            "XScale", ...
            "log", ...
            "XDir", ...
            "reverse", ...
            "YAxisLocation", ...
            "right", ...
            "XGrid", ...
            "on", ...
            "YGrid", ...
            "on", ...
            "GridLineStyle", ...
            ":", ...
            "GridAlpha", ...
            0.25, ...
            "XMinorGrid", ...
            "off", ...
            "YMinorGrid", ...
            "off");



        %% ----------------------------------------------------
        % LOAD SPECTRAL DATA
        %% ----------------------------------------------------


        frequency = ...
            R(i).spec_frequency;


        observed_power = ...
            R(i).spec_power;


        significance_95 = ...
            R(i).spec_sig95;



        %% ----------------------------------------------------
        % FREQUENCY LIMITS
        %% ----------------------------------------------------


        xlim( ...
            spectrum_axes(i), ...
            [ ...
            min(frequency) ...
            max(frequency) ...
            ]);



        %% ----------------------------------------------------
        % DISPLAY FREQUENCY-DOMAIN RESULTS AS PERIODS
        %
        % The Lomb-Scargle calculation remains in frequency
        % space.
        %
        % Only the displayed labels are converted using:
        %
        % Period = 1 / frequency
        %
        % Because XDir is reversed, the displayed order is:
        %
        % 10, 20, 50, 100 kyr
        %% ----------------------------------------------------


        spectrum_axes(i).XTick = ...
            [ ...
            1/100 ...
            1/50 ...
            1/20 ...
            1/10 ...
            ];


        spectrum_axes(i).XTickLabel = ...
            [ ...
            "100" ...
            "50" ...
            "20" ...
            "10" ...
            ];



        %% ----------------------------------------------------
        % POWER LIMITS
        %% ----------------------------------------------------


        maximum_power = ...
            max( ...
            [ ...
            observed_power(:)
            significance_95(:)
            ], ...
            [], ...
            "omitnan");


        if ...
                isempty(maximum_power) || ...
                ~isfinite(maximum_power) || ...
                maximum_power <= 0


            maximum_power = 1;


        end


        ylim( ...
            spectrum_axes(i), ...
            [ ...
            0 ...
            1.08 * maximum_power ...
            ]);


        current_ylim = ...
            ylim( ...
            spectrum_axes(i));



        %% ----------------------------------------------------
        % POWER-AXIS TICKS
        %
        % Five ticks are retained.
        %
        % The lowest and highest labels are hidden to avoid
        % overlap between adjacent panels.
        %% ----------------------------------------------------


        spectrum_axes(i).YTick = ...
            linspace( ...
            current_ylim(1), ...
            current_ylim(2), ...
            5);


        yt = ...
            spectrum_axes(i).YTick;


        ytlbl = ...
            strings( ...
            size(yt));


        for k = 1:numel(yt)


            if ...
                    abs( ...
                    yt(k) - ...
                    round(yt(k))) ...
                    < 1e-8


                ytlbl(k) = ...
                    sprintf( ...
                    "%.0f", ...
                    yt(k));


            else


                ytlbl(k) = ...
                    sprintf( ...
                    "%.1f", ...
                    yt(k));


            end


        end


        ytlbl(1) = ...
            "";


        ytlbl(end) = ...
            "";


        spectrum_axes(i).YTickLabel = ...
            ytlbl;



        %% ----------------------------------------------------
        % ORBITAL FREQUENCY LINES
        %% ----------------------------------------------------


        for orbital_number = 1:numel(orbital_frequencies)


            this_frequency = ...
                orbital_frequencies( ...
                orbital_number);


            if ...
                    this_frequency >= min(frequency) && ...
                    this_frequency <= max(frequency)


                plot( ...
                    spectrum_axes(i), ...
                    [ ...
                    this_frequency ...
                    this_frequency ...
                    ], ...
                    current_ylim, ...
                    ":", ...
                    "Color", ...
                    orbital_colours( ...
                    orbital_number, ...
                    :), ...
                    "LineWidth", ...
                    1.0, ...
                    "HandleVisibility", ...
                    "off");


            end


        end



        %% ----------------------------------------------------
        % OBSERVED LOMB-SCARGLE PSD
        %% ----------------------------------------------------


        spectrum_line = ...
            plot( ...
            spectrum_axes(i), ...
            frequency, ...
            observed_power, ...
            "Color", ...
            spectrum_colour, ...
            "LineWidth", ...
            0.85);



        %% ----------------------------------------------------
        % POINTWISE 95% AR(1) THRESHOLD
        %% ----------------------------------------------------


        significance_line = ...
            plot( ...
            spectrum_axes(i), ...
            frequency, ...
            significance_95, ...
            "--", ...
            "Color", ...
            significance_colour, ...
            "LineWidth", ...
            0.90);



        %% ----------------------------------------------------
        % AR(1) COEFFICIENT
        %% ----------------------------------------------------


        text( ...
            spectrum_axes(i), ...
            0.97, ...
            0.88, ...
            sprintf( ...
            "\\phi = %.2f", ...
            R(i).spec_ar1), ...
            "Units", ...
            "normalized", ...
            "HorizontalAlignment", ...
            "right", ...
            "VerticalAlignment", ...
            "top", ...
            "FontSize", ...
            7, ...
            "FontName", ...
            plot_opts.font_name, ...
            "Color", ...
            [0.30 0.30 0.30], ...
            "Interpreter", ...
            "tex");



        %% ----------------------------------------------------
        % ORBITAL LABELS
        %% ----------------------------------------------------


        if i == 1


            add_orbital_labels_local( ...
                spectrum_axes(i), ...
                orbital_periods, ...
                orbital_frequencies, ...
                orbital_colours, ...
                plot_opts);


        end



        %% ----------------------------------------------------
        % LEGEND
        %% ----------------------------------------------------


        if i == number_of_records


            legend( ...
                spectrum_axes(i), ...
                [ ...
                spectrum_line ...
                significance_line ...
                ], ...
                { ...
                "Lomb-Scargle PSD", ...
                "Pointwise 95% AR(1) bootstrap" ...
                }, ...
                "Location", ...
                "northeast", ...
                "Box", ...
                "off", ...
                "FontSize", ...
                7, ...
                "FontName", ...
                plot_opts.font_name);


        end



        %% ----------------------------------------------------
        % PERIOD AXIS
        %% ----------------------------------------------------


        if i == 1


            spectrum_axes(i).XAxisLocation = ...
                "top";


            xlabel( ...
                spectrum_axes(i), ...
                "Period (kyr)", ...
                "FontSize", ...
                plot_opts.xlabel_font_size, ...
                "FontWeight", ...
                "bold", ...
                "FontName", ...
                plot_opts.font_name);


        elseif i == number_of_records


            spectrum_axes(i).XAxisLocation = ...
                "bottom";


            xlabel( ...
                spectrum_axes(i), ...
                "Period (kyr)", ...
                "FontSize", ...
                plot_opts.xlabel_font_size, ...
                "FontWeight", ...
                "bold", ...
                "FontName", ...
                plot_opts.font_name);


        else


            % Hide the complete interior x-axis so that the
            % white separator remains visible between spectra.
            spectrum_axes(i).XAxis.Visible = ...
                "off";


        end



        %% ----------------------------------------------------
        % POWER LABEL
        %% ----------------------------------------------------


        if i == ceil(number_of_records / 2)


            ylabel( ...
                spectrum_axes(i), ...
                "Power spectral density", ...
                "FontSize", ...
                plot_opts.ylabel_font_size, ...
                "FontWeight", ...
                "bold", ...
                "FontName", ...
                plot_opts.font_name);


        end



        %% ----------------------------------------------------
        % PANEL LABEL
        %% ----------------------------------------------------


        add_panel_label_local( ...
            spectrum_axes(i), ...
            number_of_records + i, ...
            plot_opts);


    end



    %% --------------------------------------------------------
    % LINK AXES
    %% --------------------------------------------------------


    linkaxes( ...
        time_axes, ...
        "x");


    linkaxes( ...
        spectrum_axes, ...
        "x");



    %% --------------------------------------------------------
    % MAIN TITLE
    %% --------------------------------------------------------


    sgtitle( ...
        fig, ...
        "Hilbert amplitude and Lomb-Scargle periodograms", ...
        "FontWeight", ...
        "bold", ...
        "FontSize", ...
        plot_opts.title_font_size, ...
        "FontName", ...
        plot_opts.font_name);



    %% --------------------------------------------------------
    % APPLY FONT TO ALL OBJECTS
    %% --------------------------------------------------------


    set( ...
        findall( ...
        fig, ...
        "-property", ...
        "FontName"), ...
        "FontName", ...
        plot_opts.font_name);


end



%% ============================================================
% FUNCTION:
% ORBITAL LABELS
%% ============================================================

function add_orbital_labels_local( ...
    ax, ...
    orbital_periods, ...
    orbital_frequencies, ...
    orbital_colours, ...
    plot_opts)


    current_ylim = ...
        ylim(ax);


    y_range = ...
        current_ylim(2) - ...
        current_ylim(1);


    label_height = ...
        current_ylim(1) + ...
        0.48 * y_range;


    period_height = ...
        current_ylim(1) + ...
        0.88 * y_range;



    %% --------------------------------------------------------
    % ECCENTRICITY
    %% --------------------------------------------------------


    text( ...
        ax, ...
        orbital_frequencies(1), ...
        label_height, ...
        "Eccentricity", ...
        "Rotation", ...
        90, ...
        "HorizontalAlignment", ...
        "center", ...
        "VerticalAlignment", ...
        "bottom", ...
        "Color", ...
        orbital_colours(1, :), ...
        "FontSize", ...
        7, ...
        "FontWeight", ...
        "bold", ...
        "FontName", ...
        plot_opts.font_name, ...
        "Clipping", ...
        "on");



    %% --------------------------------------------------------
    % OBLIQUITY
    %% --------------------------------------------------------


    text( ...
        ax, ...
        orbital_frequencies(2), ...
        label_height, ...
        "Obliquity", ...
        "Rotation", ...
        90, ...
        "HorizontalAlignment", ...
        "center", ...
        "VerticalAlignment", ...
        "bottom", ...
        "Color", ...
        orbital_colours(2, :), ...
        "FontSize", ...
        7, ...
        "FontWeight", ...
        "bold", ...
        "FontName", ...
        plot_opts.font_name, ...
        "Clipping", ...
        "on");



    %% --------------------------------------------------------
    % PRECESSION
    %% --------------------------------------------------------


    precession_position = ...
        sqrt( ...
        orbital_frequencies(3) * ...
        orbital_frequencies(4));


    text( ...
        ax, ...
        precession_position, ...
        label_height, ...
        "Precession", ...
        "Rotation", ...
        90, ...
        "HorizontalAlignment", ...
        "center", ...
        "VerticalAlignment", ...
        "bottom", ...
        "Color", ...
        orbital_colours(3, :), ...
        "FontSize", ...
        7, ...
        "FontWeight", ...
        "bold", ...
        "FontName", ...
        plot_opts.font_name, ...
        "Clipping", ...
        "on");



    %% --------------------------------------------------------
    % PERIOD VALUES
    %% --------------------------------------------------------


    for k = 1:numel(orbital_periods)


        text( ...
            ax, ...
            orbital_frequencies(k), ...
            period_height, ...
            sprintf( ...
            "%d", ...
            orbital_periods(k)), ...
            "HorizontalAlignment", ...
            "center", ...
            "VerticalAlignment", ...
            "middle", ...
            "Color", ...
            orbital_colours(k, :), ...
            "FontSize", ...
            6, ...
            "FontName", ...
            plot_opts.font_name, ...
            "Clipping", ...
            "on");


    end


end



%% ============================================================
% FUNCTION:
% SET Y LIMITS
%% ============================================================

function set_nice_ylim_local( ...
    ax, ...
    y)


    y = ...
        y(isfinite(y));


    if isempty(y)


        ylim( ...
            ax, ...
            [-1 1]);


        return


    end


    minimum_y = ...
        min(y);


    maximum_y = ...
        max(y);


    y_range = ...
        maximum_y - ...
        minimum_y;


    if y_range == 0


        y_range = ...
            max( ...
            abs(maximum_y), ...
            1);


        minimum_y = ...
            minimum_y - ...
            0.5 * y_range;


        maximum_y = ...
            maximum_y + ...
            0.5 * y_range;


    end


    padding = ...
        0.08 * y_range;


    ylim( ...
        ax, ...
        [ ...
        minimum_y - padding ...
        maximum_y + padding ...
        ]);


end



%% ============================================================
% FUNCTION:
% FORMAT Y AXIS
%% ============================================================

function format_y_axis_local( ...
    ax, ...
    number_of_ticks)


    current_ylim = ...
        ylim(ax);


    y_ticks = ...
        linspace( ...
        current_ylim(1), ...
        current_ylim(2), ...
        number_of_ticks);


    ax.YTick = ...
        y_ticks;


    tick_labels = ...
        strings( ...
        size(y_ticks));


    for k = 1:numel(y_ticks)


        if ...
                abs( ...
                y_ticks(k) - ...
                round(y_ticks(k))) ...
                < 1e-8


            tick_labels(k) = ...
                sprintf( ...
                "%.0f", ...
                y_ticks(k));


        else


            tick_labels(k) = ...
                sprintf( ...
                "%.1f", ...
                y_ticks(k));


        end


    end


    tick_labels(1) = ...
        "";


    tick_labels(end) = ...
        "";


    ax.YTickLabel = ...
        tick_labels;


end



%% ============================================================
% FUNCTION:
% MIS SHADING
%% ============================================================

function add_mis_shading_local( ...
    ax, ...
    mis_intervals, ...
    plot_opts)


    current_ylim = ...
        ylim(ax);


    for j = 1:height(mis_intervals)


        start_age = ...
            mis_intervals.start_age(j);


        end_age = ...
            mis_intervals.end_age(j);


        if mis_intervals.is_interglacial(j)


            colour = ...
                plot_opts.interglacial_col;


        else


            colour = ...
                plot_opts.glacial_col;


        end


        patch( ...
            ax, ...
            [ ...
            start_age ...
            end_age ...
            end_age ...
            start_age ...
            ], ...
            [ ...
            current_ylim(1) ...
            current_ylim(1) ...
            current_ylim(2) ...
            current_ylim(2) ...
            ], ...
            colour, ...
            "FaceAlpha", ...
            1, ...
            "EdgeColor", ...
            "none", ...
            "HandleVisibility", ...
            "off");


    end


    ylim( ...
        ax, ...
        current_ylim);


end



%% ============================================================
% FUNCTION:
% MIS LABELS
%% ============================================================

function add_mis_labels_local( ...
    ax, ...
    mis_intervals, ...
    plot_opts)


    current_ylim = ...
        ylim(ax);


    % Put the MIS numbers close to the upper axis.
    % Only the number is shown, without the word "MIS".
    y_position = ...
        current_ylim(2) - ...
        0.07 * ...
        ( ...
        current_ylim(2) - ...
        current_ylim(1) ...
        );


    for j = 1:height(mis_intervals)


        midpoint = ...
            ( ...
            mis_intervals.start_age(j) + ...
            mis_intervals.end_age(j) ...
            ) / ...
            2;


        if mis_intervals.is_interglacial(j)


            colour = ...
                plot_opts.mis_interglacial_text_col;


        else


            colour = ...
                plot_opts.mis_glacial_text_col;


        end


        text( ...
            ax, ...
            midpoint, ...
            y_position, ...
            sprintf( ...
            "%g", ...
            mis_intervals.MIS(j)), ...
            "HorizontalAlignment", ...
            "center", ...
            "VerticalAlignment", ...
            "top", ...
            "FontSize", ...
            plot_opts.mis_label_font_size, ...
            "FontWeight", ...
            "bold", ...
            "FontName", ...
            plot_opts.font_name, ...
            "Color", ...
            colour, ...
            "Clipping", ...
            "on");


    end



end



%% ============================================================
% FUNCTION:
% HIATUS SHADING
%% ============================================================

function add_hiatus_markers_local( ...
    ax, ...
    record, ...
    plot_opts)


    if ...
            ~isfield(record, "hiatus_start") || ...
            isempty(record.hiatus_start)


        return


    end


    current_ylim = ...
        ylim(ax);


    for k = 1:numel(record.hiatus_start)


        start_age = ...
            record.hiatus_start(k);


        end_age = ...
            record.hiatus_end(k);


        patch( ...
            ax, ...
            [ ...
            start_age ...
            end_age ...
            end_age ...
            start_age ...
            ], ...
            [ ...
            current_ylim(1) ...
            current_ylim(1) ...
            current_ylim(2) ...
            current_ylim(2) ...
            ], ...
            plot_opts.hiatus_col, ...
            "FaceAlpha", ...
            plot_opts.hiatus_alpha, ...
            "EdgeColor", ...
            "none", ...
            "HandleVisibility", ...
            "off");


    end


    ylim( ...
        ax, ...
        current_ylim);


end



%% ============================================================
% FUNCTION:
% CUSTOM GRID
%% ============================================================

function add_custom_grid_local( ...
    ax, ...
    opts, ...
    plot_opts)


    current_xlim = ...
        xlim(ax);


    current_ylim = ...
        ylim(ax);


    x_grid = ...
        opts.age_min: ...
        plot_opts.xgrid_spacing: ...
        opts.age_max;


    for k = 1:numel(x_grid)


        plot( ...
            ax, ...
            [ ...
            x_grid(k) ...
            x_grid(k) ...
            ], ...
            current_ylim, ...
            "Color", ...
            plot_opts.grid_col, ...
            "LineWidth", ...
            plot_opts.grid_line_width, ...
            "HandleVisibility", ...
            "off");


    end


    y_ticks = ...
        ax.YTick;


    for k = 1:numel(y_ticks)


        plot( ...
            ax, ...
            current_xlim, ...
            [ ...
            y_ticks(k) ...
            y_ticks(k) ...
            ], ...
            "Color", ...
            plot_opts.grid_col, ...
            "LineWidth", ...
            plot_opts.grid_line_width, ...
            "HandleVisibility", ...
            "off");


    end


    xlim( ...
        ax, ...
        current_xlim);


    ylim( ...
        ax, ...
        current_ylim);


end



%% ============================================================
% FUNCTION:
% AXIS STYLE
%% ============================================================

function style_axis_local( ...
    ax, ...
    plot_opts)


    set( ...
        ax, ...
        "Color", ...
        plot_opts.ax_bg, ...
        "FontName", ...
        plot_opts.font_name, ...
        "FontSize", ...
        plot_opts.axis_font_size, ...
        "LineWidth", ...
        0.5, ...
        "TickDir", ...
        "out", ...
        "Layer", ...
        "top", ...
        "XGrid", ...
        "off", ...
        "YGrid", ...
        "off", ...
        "Box", ...
        "off", ...
        "XColor", ...
        [0.35 0.35 0.35], ...
        "YColor", ...
        [0.35 0.35 0.35]);


end



%% ============================================================
% FUNCTION:
% PANEL LABEL
%% ============================================================

function add_panel_label_local( ...
    ax, ...
    panel_number, ...
    plot_opts)


    letters = ...
        'abcdefghijklmnopqrstuvwxyz';


    if panel_number <= numel(letters)


        panel_text = ...
            sprintf( ...
            "(%c)", ...
            letters(panel_number));


    else


        panel_text = ...
            sprintf( ...
            "(%d)", ...
            panel_number);


    end


    text( ...
        ax, ...
        -0.10, ...
        0.84, ...
        panel_text, ...
        "Units", ...
        "normalized", ...
        "FontSize", ...
        plot_opts.panel_label_font_size, ...
        "FontWeight", ...
        "bold", ...
        "FontName", ...
        plot_opts.font_name, ...
        "Color", ...
        [0 0 0], ...
        "HorizontalAlignment", ...
        "right", ...
        "VerticalAlignment", ...
        "middle");


end