clear; close all; clc;


% FINAL ABRAM / MARRON SIZER ANALYSIS

% Uses:
%   - original Abram/Marron sz2SM_edit.m SiZer routine
%   - Hilbert amplitude already calculated by Main_Datat.m
%   - 60-100 kyr smoothing scales
%   - alpha = 0.10, simflag = 2
%   - robust onset = >= 40 kyr significant run and >= 80% support
%% ============================================================



% 1. LOAD MAIN RESULTS


results_file = "Main_Data_results.mat";


if ~isfile(results_file)

    error( ...
        'Main_Datat_results.mat was not found. Run Main_Datat.m first.');

end


S = ...
    load(results_file);


if ...
        ~isfield(S, 'R') || ...
        ~isfield(S, 'opts')

    error( ...
        'Main_Datat_results.mat must contain R and opts.');

end


R = ...
    S.R;


opts = ...
    S.opts;


if isfield(S, 'plot_opts')

    plot_opts = ...
        S.plot_opts;

else

    plot_opts = ...
        struct();

end


n_records = ...
    numel(R);


fprintf( ...
    '\nLoaded %d records from %s.\n', ...
    n_records, ...
    char(results_file));




% 2. FIND ORIGINAL ABRAM SIZER FOLDER


root_dir = ...
    pwd;


sizer_folder = ...
    find_abram_sizer_folder( ...
    root_dir);


addpath( ...
    sizer_folder);


fprintf( ...
    'Using original Abram/Marron SiZer code from:\n%s\n\n', ...
    sizer_folder);


if exist('sz2SM_edit', 'file') ~= 2

    error( ...
        'sz2SM_edit.m could not be found after adding the SiZer folder.');

end


if exist('norminv', 'file') ~= 2

    error( ...
        [ ...
        '' ...
        '' ...
        ]);

end




% 3. SIZER SETTINGS

% Minimum smoothing scale

sz.bandwidth_min = ...
    60;


% Maximum smoothing scale

sz.bandwidth_max = ...
    100;


% Gives one bandwidth at every 1 kyr:
%
% 60, 61, 62, ..., 100 kyr

sz.n_bandwidths = ...
    41;


% Approximate horizontal SiZer output resolution

sz.x_step = ...
    1.0;


% 90% confidence

sz.alpha = ...
    0.10;


% Row-wise simultaneous confidence intervals

sz.simflag = ...
    2;


% Gaussian approximation

sz.iregtdist = ...
    0;


% Original endpoint settings

sz.endpoint_flag = ...
    0;


sz.boundary_adjustment = ...
    0;




% 4. ROBUST ONSET SETTINGS



% Options:
%
% "all"
% "negative_only"
% "positive_only"

sz.onset_mode = ...
    "all";


% Minimum continuous duration of a significant SiZer trend

sz.min_run_kyr = ...
    40;


% No additional onset exclusion at individual record boundaries

sz.edge_ignore_kyr = ...
    0;


% Maximum distance between onset estimates belonging
% to the same cluster

sz.cluster_gap_kyr = 35;


% Transition must occur in at least 80% of bandwidths

sz.min_bw_fraction = ...
    0.8;


sz.min_bw_count = ...
    ceil( ...
    sz.min_bw_fraction * ...
    sz.n_bandwidths);


% Options:
%
% "p10_p90"
% "iqr"
% "range"

sz.uncertainty_mode = ...
    "p10_p90";




% 5. AGE RANGE AND FONT


age_min = ...
    get_default( ...
    opts, ...
    'age_min', ...
    0);


age_max = ...
    get_default( ...
    opts, ...
    'age_max', ...
    800);


font_name = ...
    get_default( ...
    plot_opts, ...
    'font_name', ...
    'Times New Roman');




% 6. FIXED PLOT ORDER


record_labels = ...
    lower( ...
    strtrim( ...
    string( ...
    {R.label})));


plot_order = [
    
    find_record_index( ...
    record_labels, ...
    "epica")
    
    find_record_index( ...
    record_labels, ...
    "fuji")
    
    find_record_index( ...
    record_labels, ...
    "983")
    
    find_record_index( ...
    record_labels, ...
    "speleothem")
    
    find_record_index( ...
    record_labels, ...
    "1089")
    
    find_record_index( ...
    record_labels, ...
    "1094")
    
    find_record_index( ...
    record_labels, ...
    "u1308")
    
    find_record_index( ...
    record_labels, ...
    "ps75")
    
    find_record_index( ...
    record_labels, ...
    "u1385")
    
    ];


fprintf( ...
    'Final plotting order:\n');


for k = 1:numel(plot_order)

    fprintf( ...
        '%d. %s\n', ...
        k, ...
        char( ...
        string( ...
        R( ...
        plot_order(k)).label)));

end


fprintf('\n');




% 7. FIGURE SETTINGS



figure_width = ...
    1650;


figure_height = ...
    900;




% MARGINS


left_margin = ...
    0.080;


right_margin = ...
    0.045;


top_margin = ...
    0.055;


bottom_margin = ...
    0.035;


row_gap = ...
    0.003;

x_ticks = ...
    age_min:100:age_max;


bandwidth_ticks = ...
    [60 80 100];


axis_col = ...
    [0.28 0.28 0.28];


axis_line_width = ...
    0.50;


axis_font_size = ...
    8.5;


record_font_size = ...
    9.5;


panel_font_size = ...
    9;


% Colour key:
%
% 1 = significant negative trend
%
% 2 = non-significant negative trend
%
% 3 = non-significant positive trend
%
% 4 = significant positive trend
%
% 5 = insufficient information


sizer_cmap = [

    0.05 0.20 0.75

    0.65 0.82 1.00

    1.00 0.76 0.76

    0.72 0.05 0.05

    0.90 0.90 0.90

    ];


unc_col = ...
    [0.60 0.60 0.60];


unc_alpha = ...
    0.42;


unc_boundary_col = ...
    [0 0 0];


unc_boundary_width = ...
    0.35;


unc_boundary_style = ...
    ':';


median_col = ...
    [0 0 0];


median_width = ...
    2.5;



show_timing_labels = ...
    true;


timing_font_size = ...
    9;


timing_bg = ...
    [1 1 1];


timing_margin = ...
    0.6;


save_results = ...
    true;


save_figure = ...
    true;


results_name = ...
    "SiZer_Abram_results.mat";


png_name = ...
    "SiZer_Abram_Hilbert_amplitude.png";


pdf_name = ...
    "SiZer_Abram_Hilbert_amplitude.pdf";


    '================ SIZER SETTINGS ================\n');


fprintf( ...
    'Engine: sz2SM_edit.m\n');


fprintf( ...
    'Bandwidths: %.0f-%.0f kyr (%d rows)\n', ...
    sz.bandwidth_min, ...
    sz.bandwidth_max, ...
    sz.n_bandwidths);


fprintf( ...
    'alpha = %.2f; simflag = %d\n', ...
    sz.alpha, ...
    sz.simflag);


fprintf( ...
    'Minimum run = %.0f kyr\n', ...
    sz.min_run_kyr);


fprintf( ...
    'Edge exclusion = %.0f kyr\n', ...
    sz.edge_ignore_kyr);


fprintf( ...
    'Robust support = %.0f%% = %d/%d bandwidths\n', ...
    100 * ...
    sz.min_bw_fraction, ...
    sz.min_bw_count, ...
    sz.n_bandwidths);


fprintf( ...
    'Uncertainty = %s\n', ...
    char( ...
    sz.uncertainty_mode));


fprintf( ...
    '================================================\n\n');

SZ = ...
    repmat( ...
    struct( ...
    'label', ...
    "", ...
    'age', ...
    [], ...
    'amplitude', ...
    [], ...
    'sizer_age', ...
    [], ...
    'bandwidths', ...
    [], ...
    'abram_sig90', ...
    [], ...
    'abram_sign_only', ...
    [], ...
    'class_abram', ...
    [], ...
    'class_plot', ...
    [], ...
    'all_onset_ages', ...
    [], ...
    'all_onset_bandwidths', ...
    [], ...
    'all_onset_signs', ...
    [], ...
    'clusters', ...
    []), ...
    n_records, ...
    1);


for i = 1:n_records


   
    % RECORD LABEL
   
    label = ...
        char( ...
        string( ...
        R(i).label));


    fprintf( ...
        'Calculating SiZer for %s (%d/%d)...\n', ...
        label, ...
        i, ...
        n_records);

    if ...
            ~isfield(R, 'age_hilbert') || ...
            ~isfield(R, 'hilbert_amp_z')

        error( ...
            'R must contain age_hilbert and hilbert_amp_z.');

    end

    age = ...
        R(i).age_hilbert(:);


    amp = ...
        R(i).hilbert_amp_z(:);


    valid = ...
        isfinite(age) & ...
        isfinite(amp);


    if ...
            isfield(R, 'plot_edge_keep') && ...
            numel( ...
            R(i).plot_edge_keep) == ...
            numel(age)


        valid = ...
            valid & ...
            logical( ...
            R(i).plot_edge_keep(:));


    end


    age = ...
        age(valid);


    amp = ...
        amp(valid);



    
    % CHECK RECORD LENGTH
    

    if numel(age) < 100

        error( ...
            '%s has too few valid Hilbert-amplitude values.', ...
            label);

    end



   
    % SORT BY AGE
  

    [age, idx] = ...
        sort(age);


    amp = ...
        amp(idx);



    
    % REMOVE DUPLICATE AGES
   

    [age, idx] = ...
        unique( ...
        age, ...
        'stable');


    amp = ...
        amp(idx);



   
    % ORIGINAL ABRAM/MARRON SIZER
   

    [ ...
        class_abram, ...
        class_plot, ...
        x_grid, ...
        h_grid, ...
        map90, ...
        map0 ...
        ] = ...
        run_original_sizer( ...
        age, ...
        amp, ...
        sz);

    [ ...
        onset_age, ...
        onset_bw, ...
        onset_sign ...
        ] = ...
        detect_onsets( ...
        x_grid, ...
        h_grid, ...
        class_plot, ...
        sz.onset_mode, ...
        sz.min_run_kyr, ...
        sz.edge_ignore_kyr);

    clusters = ...
        cluster_onsets( ...
        onset_age, ...
        onset_bw, ...
        onset_sign, ...
        sz.cluster_gap_kyr, ...
        sz.min_bw_count, ...
        sz.uncertainty_mode);

    SZ(i).label = ...
        string(label);


    SZ(i).age = ...
        age;


    SZ(i).amplitude = ...
        amp;


    SZ(i).sizer_age = ...
        x_grid;


    SZ(i).bandwidths = ...
        h_grid;


    SZ(i).abram_sig90 = ...
        map90;


    SZ(i).abram_sign_only = ...
        map0;


    SZ(i).class_abram = ...
        class_abram;


    SZ(i).class_plot = ...
        class_plot;


    SZ(i).all_onset_ages = ...
        onset_age;


    SZ(i).all_onset_bandwidths = ...
        onset_bw;


    SZ(i).all_onset_signs = ...
        onset_sign;


    SZ(i).clusters = ...
        clusters;


    if isempty(clusters)


        fprintf( ...
            '  No robust transition detected.\n');


    else


        for c = 1:numel(clusters)


            if clusters(c).sign < 0


                sign_text = ...
                    'negative';


            else


                sign_text = ...
                    'positive';


            end


            fprintf( ...
                [ ...
                '  Robust %s transition: ' ...
                'median %.1f kyr; ' ...
                'uncertainty %.1f-%.1f kyr; ' ...
                'support %d/%d\n' ...
                ], ...
                sign_text, ...
                clusters(c).median_age, ...
                clusters(c).unc_low_age, ...
                clusters(c).unc_high_age, ...
                clusters(c).n_bandwidths, ...
                sz.n_bandwidths);


        end


    end


end


fprintf( ...
    '\nAll SiZer calculations completed.\n');



fig = ...
    figure( ...
    'Color', ...
    'w', ...
    'Units', ...
    'pixels', ...
    'Position', ...
    [ ...
    30 ...
    30 ...
    figure_width ...
    figure_height ...
    ], ...
    'Renderer', ...
    'painters');


    numel( ...
    plot_order);


panel_h = ...
    ( ...
    1 - ...
    top_margin - ...
    bottom_margin - ...
    (n_panels - 1) * ...
    row_gap ...
    ) / ...
    n_panels;


panel_w = ...
    1 - ...
    left_margin - ...
    right_margin;


axs = ...
    gobjects( ...
    n_panels, ...
    1);


for p = 1:n_panels


    r = ...
        plot_order(p);

    y0 = ...
        1 - ...
        top_margin - ...
        p * ...
        panel_h - ...
        (p - 1) * ...
        row_gap;


    ax = ...
        axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [ ...
        left_margin ...
        y0 ...
        panel_w ...
        panel_h ...
        ]);


    axs(p) = ...
        ax;


    imagesc( ...
        ax, ...
        SZ(r).sizer_age, ...
        SZ(r).bandwidths, ...
        SZ(r).class_plot);


    set( ...
        ax, ...
        'YDir', ...
        'normal');


    colormap( ...
        ax, ...
        sizer_cmap);


    caxis( ...
        ax, ...
        [1 5]);


    hold( ...
        ax, ...
        'on');


    xlim( ...
        ax, ...
        [ ...
        age_min ...
        age_max ...
        ]);


    ylo = ...
        min( ...
        SZ(r).bandwidths);


    yhi = ...
        max( ...
        SZ(r).bandwidths);


    ylim( ...
        ax, ...
        [ ...
        ylo ...
        yhi ...
        ]);



   
    % ROBUST TRANSITIONS
    
    clusters = ...
        SZ(r).clusters;


    for c = 1:numel(clusters)


        
        % TRANSITION AGES
       

        lo = ...
            clusters(c).unc_low_age;


        hi = ...
            clusters(c).unc_high_age;


        med = ...
            clusters(c).median_age;



        
        % GREY UNCERTAINTY FILL
        %
        % No upper or lower border
        

        patch( ...
            ax, ...
            [ ...
            lo ...
            hi ...
            hi ...
            lo ...
            ], ...
            [ ...
            ylo ...
            ylo ...
            yhi ...
            yhi ...
            ], ...
            unc_col, ...
            'FaceAlpha', ...
            unc_alpha, ...
            'EdgeColor', ...
            'none', ...
            'HandleVisibility', ...
            'off');



       
        % LEFT DOTTED UNCERTAINTY BOUNDARY
       

        plot( ...
            ax, ...
            [ ...
            lo ...
            lo ...
            ], ...
            [ ...
            ylo ...
            yhi ...
            ], ...
            'LineStyle', ...
            unc_boundary_style, ...
            'Color', ...
            unc_boundary_col, ...
            'LineWidth', ...
            unc_boundary_width, ...
            'HandleVisibility', ...
            'off');



        
        % RIGHT DOTTED UNCERTAINTY BOUNDARY
       

        plot( ...
            ax, ...
            [ ...
            hi ...
            hi ...
            ], ...
            [ ...
            ylo ...
            yhi ...
            ], ...
            'LineStyle', ...
            unc_boundary_style, ...
            'Color', ...
            unc_boundary_col, ...
            'LineWidth', ...
            unc_boundary_width, ...
            'HandleVisibility', ...
            'off');



        
        % SOLID MEDIAN TIMING LINE
        

        plot( ...
            ax, ...
            [ ...
            med ...
            med ...
            ], ...
            [ ...
            ylo ...
            yhi ...
            ], ...
            '-', ...
            'Color', ...
            median_col, ...
            'LineWidth', ...
            median_width, ...
            'HandleVisibility', ...
            'off');



       
        % TIMING LABEL
      

        if show_timing_labels


            label_y = ...
                yhi - ...
                1.8 - ...
                6 * ...
                mod( ...
                c - 1, ...
                3);


            text( ...
                ax, ...
                med, ...
                label_y, ...
                sprintf( ...
                '%.0f', ...
                med), ...
                'HorizontalAlignment', ...
                'center', ...
                'VerticalAlignment', ...
                'top', ...
                'FontName', ...
                font_name, ...
                'FontSize', ...
                timing_font_size, ...
                'FontWeight', ...
                'bold', ...
                'Color', ...
                [0 0 0], ...
                'BackgroundColor', ...
                timing_bg, ...
                'Margin', ...
                timing_margin, ...
                'Clipping', ...
                'on');


        end


    end



    
    % AXIS STYLE
   

    set( ...
        ax, ...
        'Color', ...
        sizer_cmap(5, :), ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        axis_font_size, ...
        'FontWeight', ...
        'normal', ...
        'LineWidth', ...
        axis_line_width, ...
        'TickDir', ...
        'out', ...
        'Layer', ...
        'top', ...
        'Box', ...
        'off', ...
        'XColor', ...
        axis_col, ...
        'YColor', ...
        axis_col);

    ax.YTick = ...
        bandwidth_ticks;


    if p == 1


        ax.YTickLabel = ...
            { ...
            '' ...
            '80' ...
            '100' ...
            };


    elseif p == n_panels

        ax.YTickLabel = ...
            { ...
            '60' ...
            '80' ...
            '' ...
            };


    else


        ax.YTickLabel = ...
            { ...
            '' ...
            '80' ...
            '' ...
            };


    end



    % RECORD NAME
    
    ylabel( ...
        ax, ...
        SZ(r).label, ...
        'Interpreter', ...
        'none', ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        record_font_size, ...
        'FontWeight', ...
        'bold', ...
        'Color', ...
        [0.08 0.08 0.08]);



   
    % PANEL LETTER
  

    add_panel_label( ...
        ax, ...
        p, ...
        font_name, ...
        panel_font_size);



  
    % COMMON SMOOTHING-SCALE LABEL
   

    if p == ...
            ceil( ...
            n_panels / ...
            2)


        text( ...
            ax, ...
            -0.040, ...
            0.50, ...
            'Smoothing scale (kyr)', ...
            'Units', ...
            'normalized', ...
            'HorizontalAlignment', ...
            'center', ...
            'VerticalAlignment', ...
            'middle', ...
            'Rotation', ...
            90, ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            10, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            axis_col, ...
            'Clipping', ...
            'off');


    end



    
    % AGE AXIS
    

    if p == 1


       
        % TOP AGE AXIS
       

        ax.XAxisLocation = ...
            'top';


        ax.XTick = ...
            x_ticks;


        xlabel( ...
            ax, ...
            'Age BP (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            11, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            axis_col);



    elseif p == n_panels


        
        % BOTTOM AGE AXIS
      

        ax.XAxisLocation = ...
            'bottom';


        ax.XTick = ...
            x_ticks;


        xlabel( ...
            ax, ...
            'Age BP (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            11, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            axis_col);



    else


       
        % REMOVE INTERNAL X AXES
        

        ax.XTick = ...
            [];


        ax.XColor = ...
            'none';


    end


end



linkaxes( ...
    axs, ...
    'x');



set( ...
    findall( ...
    fig, ...
    '-property', ...
    'FontName'), ...
    'FontName', ...
    font_name);


drawnow;


% 17. SAVE RESULTS

if save_results


    save( ...
        results_name, ...
        'SZ', ...
        'sz', ...
        'plot_order', ...
        'sizer_folder', ...
        '-v7.3');


    fprintf( ...
        '\nResults saved as %s.\n', ...
        char(results_name));


end


% 18. SAVE FIGURE


if save_figure


    exportgraphics( ...
        fig, ...
        png_name, ...
        'Resolution', ...
        600);


    exportgraphics( ...
        fig, ...
        pdf_name, ...
        'ContentType', ...
        'vector');


    fprintf( ...
        'Figure saved as %s and %s.\n', ...
        char(png_name), ...
        char(pdf_name));


end


fprintf( ...
    '\nFinal SiZer analysis completed successfully.\n\n');


% LOCAL FUNCTION:
% FIND ABRAM SIZER FOLDER


function folder = ...
    find_abram_sizer_folder( ...
    root_dir)


    candidates = {

        fullfile( ...
        root_dir, ...
        'sizer')

        fullfile( ...
        root_dir, ...
        'AbrametalPAGES2k2016_Supp3_code', ...
        'sizer')

        };


    for i = 1:numel(candidates)


        if isfile( ...
                fullfile( ...
                candidates{i}, ...
                'sz2SM_edit.m'))


            folder = ...
                candidates{i};


            return;


        end


    end



    hit = ...
        dir( ...
        fullfile( ...
        root_dir, ...
        '**', ...
        'sz2SM_edit.m'));



    if ~isempty(hit)


        folder = ...
            hit(1).folder;


        return;


    end



    error( ...
        [ ...
        'Could not find sz2SM_edit.m. Extract the complete ' ...
        'AbrametalPAGES2k2016_Supp3_code folder beside this script.' ...
        ]);


end


% LOCAL FUNCTION:
% FIND RECORD INDEX FROM LABEL


function idx = ...
    find_record_index( ...
    labels, ...
    pattern)


    matches = ...
        find( ...
        contains( ...
        labels, ...
        lower( ...
        string(pattern))));


    if isempty(matches)


        error( ...
            'Could not find a record label containing "%s".', ...
            char(pattern));


    end



    if numel(matches) > 1


        warning( ...
            'Multiple labels contain "%s"; using the first.', ...
            char(pattern));


    end



    idx = ...
        matches(1);


end




% LOCAL FUNCTION:
% RUN ORIGINAL ABRAM / MARRON SIZER


function [ ...
    class_abram, ...
    class_plot, ...
    x_grid, ...
    h_grid, ...
    map90, ...
    map0 ...
    ] = ...
    run_original_sizer( ...
    age, ...
    y, ...
    sz)

    % PREPARE INPUT
   

    age = ...
        age(:);


    y = ...
        y(:);


    valid = ...
        isfinite(age) & ...
        isfinite(y);


    age = ...
        age(valid);


    y = ...
        y(valid);


    [age, idx] = ...
        sort(age);


    y = ...
        y(idx);
 
    % SIZER GRID
   

    xmin = ...
        min(age);


    xmax = ...
        max(age);


    nbin = ...
        max( ...
        round( ...
        ( ...
        xmax - ...
        xmin ...
        ) / ...
        sz.x_step) + ...
        1, ...
        101);


    % REGRESSION INPUT
   

    data = ...
        [ ...
        age ...
        y ...
        ];

    % ORIGINAL SIZER PARAMETERS
 

    par = ...
        struct( ...
        'vxgp', ...
        [ ...
        xmin
        xmax
        nbin ...
        ], ...
        'vhgp', ...
        [ ...
        sz.bandwidth_min
        sz.bandwidth_max
        sz.n_bandwidths ...
        ], ...
        'eptflag', ...
        sz.endpoint_flag, ...
        'ibdryadj', ...
        sz.boundary_adjustment, ...
        'iregtdist', ...
        sz.iregtdist, ...
        'simflag', ...
        sz.simflag, ...
        'icolor', ...
        1, ...
        'iplot', ...
        0);


    % 90% SIGNIFICANCE MAP
   

    par.alpha = ...
        sz.alpha;


    [ ...
        map90, ...
        x_grid ...
        ] = ...
        sz2SM_edit( ...
        data, ...
        par);



  
    % ALPHA = 1:
    % SIGN OF THE DERIVATIVE ONLY
   

    par.alpha = ...
        1;


    [ ...
        map0, ...
        x_grid0 ...
        ] = ...
        sz2SM_edit( ...
        data, ...
        par);



    % CHECK AGE GRIDS
  

    x_grid = ...
        x_grid(:)';


    x_grid0 = ...
        x_grid0(:)';


    if ...
            numel(x_grid) ~= ...
            numel(x_grid0) || ...
            any( ...
            abs( ...
            x_grid - ...
            x_grid0) > ...
            1e-10)


        error( ...
            'The alpha = 0.10 and alpha = 1 SiZer grids differ.');


    end


    h_grid = ...
        linspace( ...
        sz.bandwidth_min, ...
        sz.bandwidth_max, ...
        sz.n_bandwidths);


    if ...
            size(map90, 1) ~= ...
            numel(h_grid) && ...
            size(map90, 2) == ...
            numel(h_grid)


        map90 = ...
            map90';


    end



    if ...
            size(map0, 1) ~= ...
            numel(h_grid) && ...
            size(map0, 2) == ...
            numel(h_grid)


        map0 = ...
            map0';


    end



    if ...
            size(map90, 1) ~= ...
            numel(h_grid) || ...
            size(map90, 2) ~= ...
            numel(x_grid)


        error( ...
            'Unexpected output dimensions from sz2SM_edit.m.');


    end



    if ~isequal( ...
            size(map90), ...
            size(map0))


        error( ...
            'The alpha = 0.10 and alpha = 1 maps differ in size.');


    end



 
 
    % Original combined key:
    %
    % 1 = significant positive trend
    %
    % 2 = non-significant positive trend
    %
    % 3 = non-significant negative trend
    %
    % 4 = significant negative trend
    %
    % -999 = insufficient information
    

    z90 = ...
        double(map90);


    z0 = ...
        double(map0);


    z90( ...
        z90 == 2) = ...
        -999;


    z0( ...
        z0 == 2) = ...
        -999;


    class_abram = ...
        ( ...
        z0 + ...
        z90 ...
        ) / ...
        2;


    class_abram( ...
        abs( ...
        class_abram - ...
        3.5) < ...
        1e-12) = ...
        3;


    class_abram( ...
        class_abram < 0) = ...
        -999;



    
    % REMAP FOR THE CHOSEN FIGURE COLOURS
    %
    % 1 = significant negative
    %
    % 2 = non-significant negative
    %
    % 3 = non-significant positive
    %
    % 4 = significant positive
    %
    % 5 = insufficient information
  

    class_plot = ...
        5 * ...
        ones( ...
        size( ...
        class_abram));


    ok = ...
        class_abram >= 1 & ...
        class_abram <= 4;


    class_plot(ok) = ...
        5 - ...
        class_abram(ok);


end

function [ ...
    ages, ...
    bws, ...
    signs ...
    ] = ...
    detect_onsets( ...
    x, ...
    h, ...
    C, ...
    mode, ...
    min_run, ...
    edge_ignore)


    ages = ...
        [];


    bws = ...
        [];


    signs = ...
        [];


    young_limit = ...
        min(x) + ...
        edge_ignore;


    old_limit = ...
        max(x) - ...
        edge_ignore;



    for ih = 1:numel(h)


        row = ...
            C(ih, :);


        neg = ...
            get_runs( ...
            x, ...
            row == 1, ...
            min_run, ...
            young_limit, ...
            old_limit);


        pos = ...
            get_runs( ...
            x, ...
            row == 4, ...
            min_run, ...
            young_limit, ...
            old_limit);

        switch lower( ...
                string(mode))


            case "negative_only"


                [ ...
                    ages, ...
                    bws, ...
                    signs ...
                    ] = ...
                    append_runs( ...
                    ages, ...
                    bws, ...
                    signs, ...
                    neg, ...
                    h(ih), ...
                    -1);



            case "positive_only"


                [ ...
                    ages, ...
                    bws, ...
                    signs ...
                    ] = ...
                    append_runs( ...
                    ages, ...
                    bws, ...
                    signs, ...
                    pos, ...
                    h(ih), ...
                    1);



            case "all"


                [ ...
                    ages, ...
                    bws, ...
                    signs ...
                    ] = ...
                    append_runs( ...
                    ages, ...
                    bws, ...
                    signs, ...
                    neg, ...
                    h(ih), ...
                    -1);


                [ ...
                    ages, ...
                    bws, ...
                    signs ...
                    ] = ...
                    append_runs( ...
                    ages, ...
                    bws, ...
                    signs, ...
                    pos, ...
                    h(ih), ...
                    1);



            otherwise


                error( ...
                    'Unknown onset mode: %s', ...
                    char(mode));


        end


    end


end



function [ ...
    ages, ...
    bws, ...
    signs ...
    ] = ...
    append_runs( ...
    ages, ...
    bws, ...
    signs, ...
    runs, ...
    bw, ...
    sgn)


    for k = 1:numel(runs)


        ages( ...
            end + 1, ...
            1) = ...
            runs(k).old_edge_age;


        bws( ...
            end + 1, ...
            1) = ...
            bw;


        signs( ...
            end + 1, ...
            1) = ...
            sgn;


    end


end


function runs = ...
    get_runs( ...
    age, ...
    mask, ...
    min_run, ...
    young_limit, ...
    old_limit)


    age = ...
        age(:);


    mask = ...
        logical( ...
        mask(:)');


    runs = ...
        struct( ...
        'young_edge_age', ...
        {}, ...
        'old_edge_age', ...
        {}, ...
        'duration', ...
        {});


    if ...
            isempty(mask) || ...
            ~any(mask)


        return;


    end



    difference = ...
        diff( ...
        [ ...
        0 ...
        mask ...
        0 ...
        ]);


    start_indices = ...
        find( ...
        difference == 1);


    end_indices = ...
        find( ...
        difference == -1) - ...
        1;



    for k = 1:numel(start_indices)


        young = ...
            age( ...
            start_indices(k));


        old = ...
            age( ...
            end_indices(k));


        duration = ...
            old - ...
            young;



        if ...
                old <= ...
                young_limit || ...
                old >= ...
                old_limit


            continue;


        end



        if duration >= ...
                min_run


            runs( ...
                end + 1).young_edge_age = ...
                young;


            runs(end).old_edge_age = ...
                old;


            runs(end).duration = ...
                duration;


        end


    end


end



function clusters = ...
    cluster_onsets( ...
    ages, ...
    bws, ...
    signs, ...
    gap, ...
    min_bws, ...
    unc_mode)


    clusters = ...
        struct( ...
        'median_age', ...
        {}, ...
        'p10_age', ...
        {}, ...
        'p90_age', ...
        {}, ...
        'q25_age', ...
        {}, ...
        'q75_age', ...
        {}, ...
        'unc_low_age', ...
        {}, ...
        'unc_high_age', ...
        {}, ...
        'sign', ...
        {}, ...
        'n_points', ...
        {}, ...
        'n_bandwidths', ...
        {}, ...
        'ages', ...
        {}, ...
        'bandwidths', ...
        {});


    if isempty(ages)


        return;


    end



    sign_values = ...
        unique( ...
        signs( ...
        isfinite( ...
        signs)));



    for ss = 1:numel(sign_values)


        this_sign = ...
            sign_values(ss);


        use = ...
            signs == ...
            this_sign & ...
            isfinite(ages) & ...
            isfinite(bws);


        a = ...
            ages(use);


        b = ...
            bws(use);


        if isempty(a)


            continue;


        end



        [a, idx] = ...
            sort(a);


        b = ...
            b(idx);


        current_a = ...
            a(1);


        current_b = ...
            b(1);



        for i = 2:numel(a)


            if ...
                    a(i) - ...
                    a(i - 1) <= ...
                    gap


                current_a( ...
                    end + 1, ...
                    1) = ...
                    a(i);


                current_b( ...
                    end + 1, ...
                    1) = ...
                    b(i);


            else


                clusters = ...
                    add_cluster( ...
                    clusters, ...
                    current_a, ...
                    current_b, ...
                    this_sign, ...
                    min_bws, ...
                    unc_mode);


                current_a = ...
                    a(i);


                current_b = ...
                    b(i);


            end


        end



        clusters = ...
            add_cluster( ...
            clusters, ...
            current_a, ...
            current_b, ...
            this_sign, ...
            min_bws, ...
            unc_mode);


    end



    if ~isempty(clusters)


        [~, idx] = ...
            sort( ...
            [ ...
            clusters.median_age ...
            ], ...
            'descend');


        clusters = ...
            clusters(idx);


    end


end



function clusters = ...
    add_cluster( ...
    clusters, ...
    ages, ...
    bws, ...
    sgn, ...
    min_bws, ...
    unc_mode)


    unique_bws = ...
        unique(bws);


    if numel(unique_bws) < ...
            min_bws


        return;


    end



    p10 = ...
        local_percentile( ...
        ages, ...
        10);


    p90 = ...
        local_percentile( ...
        ages, ...
        90);


    q25 = ...
        local_percentile( ...
        ages, ...
        25);


    q75 = ...
        local_percentile( ...
        ages, ...
        75);



    switch lower( ...
            string( ...
            unc_mode))


        case "p10_p90"


            lo = ...
                p10;


            hi = ...
                p90;



        case "iqr"


            lo = ...
                q25;


            hi = ...
                q75;



        case "range"


            lo = ...
                min( ...
                ages, ...
                [], ...
                'omitnan');


            hi = ...
                max( ...
                ages, ...
                [], ...
                'omitnan');



        otherwise


            error( ...
                'Unknown uncertainty mode: %s', ...
                char( ...
                unc_mode));


    end



    clusters( ...
        end + 1).median_age = ...
        median( ...
        ages, ...
        'omitnan');


    clusters(end).p10_age = ...
        p10;


    clusters(end).p90_age = ...
        p90;


    clusters(end).q25_age = ...
        q25;


    clusters(end).q75_age = ...
        q75;


    clusters(end).unc_low_age = ...
        lo;


    clusters(end).unc_high_age = ...
        hi;


    clusters(end).sign = ...
        sgn;


    clusters(end).n_points = ...
        numel(ages);


    clusters(end).n_bandwidths = ...
        numel(unique_bws);


    clusters(end).ages = ...
        ages;


    clusters(end).bandwidths = ...
        bws;


end



function v = ...
    local_percentile( ...
    x, ...
    p)


    x = ...
        sort( ...
        x( ...
        isfinite(x)));


    if isempty(x)


        v = ...
            NaN;


        return;


    end



    x = ...
        x(:);


    n = ...
        numel(x);


    if n == 1


        v = ...
            x;


        return;


    end



    position = ...
        1 + ...
        ( ...
        p / ...
        100 ...
        ) * ...
        ( ...
        n - ...
        1 ...
        );


    lo = ...
        floor( ...
        position);


    hi = ...
        ceil( ...
        position);



    if lo == hi


        v = ...
            x(lo);


    else


        weight = ...
            position - ...
            lo;


        v = ...
            ( ...
            1 - ...
            weight ...
            ) * ...
            x(lo) + ...
            weight * ...
            x(hi);


    end


end


function add_panel_label( ...
    ax, ...
    n, ...
    font_name, ...
    font_size)


    letters = ...
        'abcdefghijklmnopqrstuvwxyz';


    if n <= ...
            numel(letters)


        txt = ...
            sprintf( ...
            '(%c)', ...
            letters(n));


    else


        txt = ...
            sprintf( ...
            '(%d)', ...
            n);


    end



    text( ...
        ax, ...
        -0.056, ...
        0.88, ...
        txt, ...
        'Units', ...
        'normalized', ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'middle', ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        font_size, ...
        'FontWeight', ...
        'bold', ...
        'Color', ...
        [0 0 0], ...
        'Clipping', ...
        'off');


end



function value = ...
    get_default( ...
    S, ...
    field_name, ...
    default_value)


    if ...
            isstruct(S) && ...
            isfield( ...
            S, ...
            field_name)


        value = ...
            S.(field_name);


    else


        value = ...
            default_value;


    end


end