%% SYNTHETIC EPICA RESOLUTION TEST
% Comparison of:
%   1. Thirumalai-style <10 kyr rolling-standard-deviation metric
%   2. Thesis-style 2--10 kyr Hilbert-amplitude metric
%
% Experimental design:
%
%   1. Generate stationary AR(1) records on a uniform 100-year grid.
%
%   2. Standardise every AR(1) realisation separately and scale it to the
%      EPICA-derived residual standard deviation.
%
%   3. Create two versions of every realisation:
%
%      Uniform control:
%         100-year record
%         -> PCHIP interpolation to 250-, 500-, or 750-year grid
%
%      EPICA-resolution record:
%         100-year record
%         -> sampling at the original EPICA observation ages
%         -> PCHIP interpolation to 250-, 500-, or 750-year grid
%
%   4. Apply both mMCV definitions only after the control and degraded
%      records have been placed on the same target grid.
%
%   5. Smooth each resulting mMCV curve using a 100-kyr Gaussian window.
%
%   6. Calculate percentage bias separately for each paired realisation:
%
%      100 * (EPICA-resolution - uniform control) / uniform control
%
%   7. Plot:
%      - ensemble mean;
%      - 5th--95th percentile range.

clear;
close all;
clc;


% 1. SETTINGS

opts = struct();

% EPICA input file.
opts.epica_file = "Epica_deuterium.txt";

% EPICA age interval used.
opts.age_min_kyr = 0;
opts.age_max_kyr = 801;

% Original resolution of every synthetic record.
opts.base_dt_kyr = 0.10;          % 100 years

% Target analysis grids.
opts.test_dt_kyr = [0.25, 0.50, 0.75];

% Common grid used only for ensemble storage and plotting.
opts.output_dt_kyr = 1.0;

% Interpolation.
opts.interp_method = "pchip";

% Filtering.
opts.filter_order = 4;
opts.pad_kyr = 10;

% Thirumalai-style definition.
opts.thirumalai_cutoff_kyr = 10;
opts.rolling_window_kyr = 2;

% Thesis-style Hilbert definition.
opts.hilbert_lower_period_kyr = 2;
opts.hilbert_upper_period_kyr = 10;

% Long-term smoothing.
opts.trend_window_kyr = 100;

% EPICA residual calculation for AR(1) parameter estimation.
opts.parameter_smooth_kyr = 100;

% AR(1) burn-in.
opts.burn_in_steps = 2000;

% Monte Carlo experiment.
%
% Use 100 initially to check that the code runs correctly.
% Change to 10000 for the final analysis.
opts.n_realizations = 10000;

% Number of realisations processed simultaneously.
opts.chunk_size = 50;

% Reproducible random-number sequence.
opts.random_seed = 20260718;

% Ensemble range.
opts.lower_percentile = 5;
opts.upper_percentile = 95;

% Numerical summary interval.
opts.summary_interval_kyr = [600, 750];


% 2. FIGURE SETTINGS

opts.font_name = "Cambria Math";

opts.axis_font_size = 17;
opts.title_font_size = 18;
opts.label_font_size = 18;
opts.legend_font_size = 14;
opts.panel_font_size = 18;

opts.background_colour = [0.975, 0.935, 0.945];
opts.grid_colour = [1, 1, 1];
opts.grid_alpha = 0.30;

opts.line_width = 1.60;

control_colour = [0.15, 0.40, 0.80];
epica_colour = [0.85, 0.25, 0.25];

bias_colours = [ ...
    0.15, 0.40, 0.80; ...
    0.85, 0.25, 0.25; ...
    0.20, 0.60, 0.35];

% 3. READ THE EPICA RECORD

[age_obs, deltaD_obs] = read_epica_record( ...
    opts.epica_file, ...
    opts.age_min_kyr, ...
    opts.age_max_kyr);

fprintf("\n============================================================\n");
fprintf("EPICA RESOLUTION TEST\n");
fprintf("============================================================\n");
fprintf("Number of EPICA observations: %d\n", numel(age_obs));
fprintf("EPICA age range: %.2f--%.2f kyr BP\n", ...
    min(age_obs), max(age_obs));


% 4. CREATE THE UNIFORM 100-YEAR BASE GRID


age_base_start = ...
    ceil(max(opts.age_min_kyr, min(age_obs)) / opts.base_dt_kyr) ...
    * opts.base_dt_kyr;

age_base_end = ...
    floor(min(opts.age_max_kyr, max(age_obs)) / opts.base_dt_kyr) ...
    * opts.base_dt_kyr;

age_base = ...
    (age_base_start:opts.base_dt_kyr:age_base_end)';

% Restrict EPICA observation ages to the base-grid interval.
keep_obs = ...
    age_obs >= age_base(1) ...
    & age_obs <= age_base(end);

age_obs = age_obs(keep_obs);
deltaD_obs = deltaD_obs(keep_obs);

% Interpolate observed EPICA onto the 100-year grid.
%
% This interpolated EPICA record is used only to estimate phi and
% sigma_proxy. It is not used as a synthetic control.
deltaD_base = interp1( ...
    age_obs, ...
    deltaD_obs, ...
    age_base, ...
    opts.interp_method);


% 5. CREATE THE COMMON OUTPUT GRID


age_output_start = ...
    ceil(age_base(1) / opts.output_dt_kyr) ...
    * opts.output_dt_kyr;

age_output_end = ...
    floor(age_base(end) / opts.output_dt_kyr) ...
    * opts.output_dt_kyr;

age_output = ...
    (age_output_start:opts.output_dt_kyr:age_output_end)';


% 6. ESTIMATE EPICA-DERIVED AR(1) PARAMETERS


% Remove the long-term EPICA background.
EPICA_long_term = gaussian_smooth_matrix( ...
    deltaD_base, ...
    opts.base_dt_kyr, ...
    opts.parameter_smooth_kyr);

EPICA_residual = ...
    deltaD_base - EPICA_long_term;

% Estimate lag-1 autocorrelation.
x_previous = EPICA_residual(1:end-1);
x_next = EPICA_residual(2:end);

valid_pairs = ...
    isfinite(x_previous) ...
    & isfinite(x_next);

phi_proxy = corr( ...
    x_previous(valid_pairs), ...
    x_next(valid_pairs));

% Avoid an exactly non-stationary AR(1) process.
phi_proxy = max(min(phi_proxy, 0.999), -0.999);

% Target standard deviation for every synthetic realisation.
sigma_proxy = std( ...
    EPICA_residual, ...
    0, ...
    "omitnan");

% Longer burn-in for highly persistent AR(1) processes.
adaptive_burn_in = ceil( ...
    20 / max(1 - abs(phi_proxy), 1e-4));

burn_in = max( ...
    opts.burn_in_steps, ...
    adaptive_burn_in);

fprintf("\nEPICA-derived synthetic parameters:\n");
fprintf("AR(1) phi: %.6f\n", phi_proxy);
fprintf("Target synthetic SD: %.6f\n", sigma_proxy);
fprintf("Burn-in: %d time steps\n", burn_in);
fprintf("Synthetic base grid: %.0f years\n", ...
    1000 * opts.base_dt_kyr);
fprintf("Number of realisations: %d\n", ...
    opts.n_realizations);


% 7. CREATE THE TARGET ANALYSIS GRIDS


n_grid = numel(opts.test_dt_kyr);

GRID = cell(n_grid, 1);

for i_grid = 1:n_grid

    dt = opts.test_dt_kyr(i_grid);

    target_start = ...
        ceil(age_base(1) / dt) * dt;

    target_end = ...
        floor(age_base(end) / dt) * dt;

    GRID{i_grid}.dt_kyr = dt;

    GRID{i_grid}.grid_years = ...
        round(1000 * dt);

    GRID{i_grid}.age = ...
        (target_start:dt:target_end)';

    fprintf( ...
        "%d-year grid: %d points, %.2f--%.2f kyr BP\n", ...
        GRID{i_grid}.grid_years, ...
        numel(GRID{i_grid}.age), ...
        GRID{i_grid}.age(1), ...
        GRID{i_grid}.age(end));

end


% 8. PREALLOCATE ENSEMBLE OUTPUT ARRAYS


n_output = numel(age_output);
n_real = opts.n_realizations;

THIR_Z_CONTROL = cell(n_grid, 1);
THIR_Z_EPICA = cell(n_grid, 1);

HILBERT_Z_CONTROL = cell(n_grid, 1);
HILBERT_Z_EPICA = cell(n_grid, 1);

THIR_PERCENT_BIAS = cell(n_grid, 1);
HILBERT_PERCENT_BIAS = cell(n_grid, 1);

for i_grid = 1:n_grid

    THIR_Z_CONTROL{i_grid} = ...
        nan(n_output, n_real, "single");

    THIR_Z_EPICA{i_grid} = ...
        nan(n_output, n_real, "single");

    HILBERT_Z_CONTROL{i_grid} = ...
        nan(n_output, n_real, "single");

    HILBERT_Z_EPICA{i_grid} = ...
        nan(n_output, n_real, "single");

    THIR_PERCENT_BIAS{i_grid} = ...
        nan(n_output, n_real, "single");

    HILBERT_PERCENT_BIAS{i_grid} = ...
        nan(n_output, n_real, "single");

end


% 9. PAIRED MONTE CARLO EXPERIMENT


rng(opts.random_seed, "twister");

fprintf("\n============================================================\n");
fprintf("RUNNING MONTE CARLO EXPERIMENT\n");
fprintf("============================================================\n");

for first_realisation = 1:opts.chunk_size:opts.n_realizations

    last_realisation = min( ...
        first_realisation + opts.chunk_size - 1, ...
        opts.n_realizations);

    column_indices = ...
        first_realisation:last_realisation;

    n_chunk = numel(column_indices);

    fprintf( ...
        "Realisations %d--%d of %d\n", ...
        first_realisation, ...
        last_realisation, ...
        opts.n_realizations);

    
    % 9.1 Generate AR(1) records on the original 100-year grid
 

    % Unit Gaussian innovations.
    innovations = randn( ...
        numel(age_base) + burn_in, ...
        n_chunk);

    % AR(1):
    %
    % X(t) = phi * X(t-1) + eta(t)
    synthetic_full = filter( ...
        1, ...
        [1, -phi_proxy], ...
        innovations, ...
        [], ...
        1);

    % Remove burn-in.
    synthetic_100yr = ...
        synthetic_full(burn_in + 1:end, :);

    % Standardise every realisation separately and scale it to the
    % EPICA-derived residual standard deviation.
    synthetic_100yr = standardise_to_sigma( ...
        synthetic_100yr, ...
        sigma_proxy);

    
    % 9.2 Sample each 100-year record at the original EPICA ages
    

    synthetic_at_EPICA_ages = interp1( ...
        age_base, ...
        synthetic_100yr, ...
        age_obs, ...
        opts.interp_method);

    
    % 9.3 Process each target analysis grid
    

    for i_grid = 1:n_grid

        dt = GRID{i_grid}.dt_kyr;
        age_target = GRID{i_grid}.age;

        % Uniform control:
        %
        % 100-year synthetic record
        % -> target grid.
        synthetic_control = interp1( ...
            age_base, ...
            synthetic_100yr, ...
            age_target, ...
            opts.interp_method);

        % EPICA-resolution record:
        %
        % 100-year synthetic record
        % -> original EPICA ages
        % -> target grid.
        synthetic_EPICA = interp1( ...
            age_obs, ...
            synthetic_at_EPICA_ages, ...
            age_target, ...
            opts.interp_method);

       
        % 9.4 Thirumalai-style metric
     

        thir_control_raw = thirumalai_metric_raw( ...
            synthetic_control, ...
            dt, ...
            opts);

        thir_EPICA_raw = thirumalai_metric_raw( ...
            synthetic_EPICA, ...
            dt, ...
            opts);

        % Joint standardisation ensures that the control and degraded
        % curves use the same z-score scale within each realisation.
        [thir_control_z, thir_EPICA_z] = ...
            joint_zscore_pair( ...
            thir_control_raw, ...
            thir_EPICA_raw);

        % Smooth the z-score curves.
        thir_control_z_smooth = gaussian_smooth_matrix( ...
            thir_control_z, ...
            dt, ...
            opts.trend_window_kyr);

        thir_EPICA_z_smooth = gaussian_smooth_matrix( ...
            thir_EPICA_z, ...
            dt, ...
            opts.trend_window_kyr);

        % Smooth the raw, positive metrics before percentage calculation.
        thir_control_raw_smooth = gaussian_smooth_matrix( ...
            thir_control_raw, ...
            dt, ...
            opts.trend_window_kyr);

        thir_EPICA_raw_smooth = gaussian_smooth_matrix( ...
            thir_EPICA_raw, ...
            dt, ...
            opts.trend_window_kyr);

        % Calculate percentage bias separately for every paired
        % realisation.
        thir_percent_bias = calculate_percentage_bias( ...
            thir_control_raw_smooth, ...
            thir_EPICA_raw_smooth);

        
        % 9.5 Thesis-style 2--10 kyr Hilbert-amplitude metric
      

        hilbert_control_raw = hilbert_metric_raw( ...
            synthetic_control, ...
            dt, ...
            opts);

        hilbert_EPICA_raw = hilbert_metric_raw( ...
            synthetic_EPICA, ...
            dt, ...
            opts);

        [hilbert_control_z, hilbert_EPICA_z] = ...
            joint_zscore_pair( ...
            hilbert_control_raw, ...
            hilbert_EPICA_raw);

        hilbert_control_z_smooth = gaussian_smooth_matrix( ...
            hilbert_control_z, ...
            dt, ...
            opts.trend_window_kyr);

        hilbert_EPICA_z_smooth = gaussian_smooth_matrix( ...
            hilbert_EPICA_z, ...
            dt, ...
            opts.trend_window_kyr);

        hilbert_control_raw_smooth = gaussian_smooth_matrix( ...
            hilbert_control_raw, ...
            dt, ...
            opts.trend_window_kyr);

        hilbert_EPICA_raw_smooth = gaussian_smooth_matrix( ...
            hilbert_EPICA_raw, ...
            dt, ...
            opts.trend_window_kyr);

        hilbert_percent_bias = calculate_percentage_bias( ...
            hilbert_control_raw_smooth, ...
            hilbert_EPICA_raw_smooth);

        
        % 9.6 Interpolate finished smoothed curves to the common output grid
       

        THIR_Z_CONTROL{i_grid}(:, column_indices) = single( ...
            interp1( ...
            age_target, ...
            thir_control_z_smooth, ...
            age_output, ...
            "linear"));

        THIR_Z_EPICA{i_grid}(:, column_indices) = single( ...
            interp1( ...
            age_target, ...
            thir_EPICA_z_smooth, ...
            age_output, ...
            "linear"));

        HILBERT_Z_CONTROL{i_grid}(:, column_indices) = single( ...
            interp1( ...
            age_target, ...
            hilbert_control_z_smooth, ...
            age_output, ...
            "linear"));

        HILBERT_Z_EPICA{i_grid}(:, column_indices) = single( ...
            interp1( ...
            age_target, ...
            hilbert_EPICA_z_smooth, ...
            age_output, ...
            "linear"));

        THIR_PERCENT_BIAS{i_grid}(:, column_indices) = single( ...
            interp1( ...
            age_target, ...
            thir_percent_bias, ...
            age_output, ...
            "linear"));

        HILBERT_PERCENT_BIAS{i_grid}(:, column_indices) = single( ...
            interp1( ...
            age_target, ...
            hilbert_percent_bias, ...
            age_output, ...
            "linear"));

    end

end

fprintf("\nMonte Carlo experiment completed.\n");


% 10. CALCULATE ENSEMBLE MEANS AND 5--95% RANGES


RESULTS = cell(n_grid, 1);

for i_grid = 1:n_grid

    R = struct();

    R.dt_kyr = GRID{i_grid}.dt_kyr;
    R.grid_years = GRID{i_grid}.grid_years;
    R.age = age_output;

    R.thir_control_z = ensemble_mean_and_range( ...
        THIR_Z_CONTROL{i_grid}, ...
        opts.lower_percentile, ...
        opts.upper_percentile);

    R.thir_EPICA_z = ensemble_mean_and_range( ...
        THIR_Z_EPICA{i_grid}, ...
        opts.lower_percentile, ...
        opts.upper_percentile);

    R.hilbert_control_z = ensemble_mean_and_range( ...
        HILBERT_Z_CONTROL{i_grid}, ...
        opts.lower_percentile, ...
        opts.upper_percentile);

    R.hilbert_EPICA_z = ensemble_mean_and_range( ...
        HILBERT_Z_EPICA{i_grid}, ...
        opts.lower_percentile, ...
        opts.upper_percentile);

    R.thir_percent_bias = ensemble_mean_and_range( ...
        THIR_PERCENT_BIAS{i_grid}, ...
        opts.lower_percentile, ...
        opts.upper_percentile);

    R.hilbert_percent_bias = ensemble_mean_and_range( ...
        HILBERT_PERCENT_BIAS{i_grid}, ...
        opts.lower_percentile, ...
        opts.upper_percentile);

    RESULTS{i_grid} = R;

end


% 11. DISPLAY NUMERICAL SUMMARY


summary_interval = ...
    age_output >= opts.summary_interval_kyr(1) ...
    & age_output <= opts.summary_interval_kyr(2);

Grid_years = nan(n_grid, 1);

Thir_full_record_mean_bias_percent = nan(n_grid, 1);
Hilbert_full_record_mean_bias_percent = nan(n_grid, 1);

Thir_600_750ka_mean_bias_percent = nan(n_grid, 1);
Hilbert_600_750ka_mean_bias_percent = nan(n_grid, 1);

Thir_600_750ka_minimum_bias_percent = nan(n_grid, 1);
Hilbert_600_750ka_minimum_bias_percent = nan(n_grid, 1);

for i_grid = 1:n_grid

    R = RESULTS{i_grid};

    Grid_years(i_grid) = ...
        R.grid_years;

    Thir_full_record_mean_bias_percent(i_grid) = mean( ...
        R.thir_percent_bias.mean, ...
        "omitnan");

    Hilbert_full_record_mean_bias_percent(i_grid) = mean( ...
        R.hilbert_percent_bias.mean, ...
        "omitnan");

    Thir_600_750ka_mean_bias_percent(i_grid) = mean( ...
        R.thir_percent_bias.mean(summary_interval), ...
        "omitnan");

    Hilbert_600_750ka_mean_bias_percent(i_grid) = mean( ...
        R.hilbert_percent_bias.mean(summary_interval), ...
        "omitnan");

    Thir_600_750ka_minimum_bias_percent(i_grid) = min( ...
        R.thir_percent_bias.mean(summary_interval), ...
        [], ...
        "omitnan");

    Hilbert_600_750ka_minimum_bias_percent(i_grid) = min( ...
        R.hilbert_percent_bias.mean(summary_interval), ...
        [], ...
        "omitnan");

end

SummaryTable = table( ...
    Grid_years, ...
    Thir_full_record_mean_bias_percent, ...
    Hilbert_full_record_mean_bias_percent, ...
    Thir_600_750ka_mean_bias_percent, ...
    Hilbert_600_750ka_mean_bias_percent, ...
    Thir_600_750ka_minimum_bias_percent, ...
    Hilbert_600_750ka_minimum_bias_percent);

fprintf("\n============================================================\n");
fprintf("RESOLUTION-BIAS SUMMARY\n");
fprintf("============================================================\n");

disp(SummaryTable);


% 12. FIGURE 1: JOINT Z-SCORE COMPARISON


fig_zscore = figure( ...
    "Color", "w", ...
    "Units", "pixels", ...
    "Position", [30, 30, 1600, 900], ...
    "Renderer", "painters");

Tz = tiledlayout( ...
    fig_zscore, ...
    2, ...
    3, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

zscore_axes = gobjects(6, 1);

for i_grid = 1:n_grid

    R = RESULTS{i_grid};

    %% Top row: Thirumalai-style metric

    ax_thir = nexttile(Tz, i_grid);
    zscore_axes(i_grid) = ax_thir;

    hold(ax_thir, "on");

    plot_percentile_band( ...
        ax_thir, ...
        age_output, ...
        R.thir_control_z.lower, ...
        R.thir_control_z.upper, ...
        control_colour, ...
        0.16);

    plot_percentile_band( ...
        ax_thir, ...
        age_output, ...
        R.thir_EPICA_z.lower, ...
        R.thir_EPICA_z.upper, ...
        epica_colour, ...
        0.16);

    h_control = plot( ...
        ax_thir, ...
        age_output, ...
        R.thir_control_z.mean, ...
        "Color", control_colour, ...
        "LineWidth", opts.line_width);

    h_EPICA = plot( ...
        ax_thir, ...
        age_output, ...
        R.thir_EPICA_z.mean, ...
        "Color", epica_colour, ...
        "LineWidth", opts.line_width);

    title( ...
        ax_thir, ...
        sprintf("%d-year grid", R.grid_years));

    style_axis(ax_thir, opts);

    ax_thir.XTickLabel = [];

    add_panel_label( ...
        ax_thir, ...
        char('a' + i_grid - 1), ...
        opts);

    if i_grid == 1

        ylabel( ...
            ax_thir, ...
            "Thirumalai-style mMCV (z-score)");

        legend( ...
            ax_thir, ...
            [h_control, h_EPICA], ...
            { ...
            "Uniform control", ...
            "EPICA resolution" ...
            }, ...
            "Location", "northwest", ...
            "Box", "off", ...
            "FontName", opts.font_name, ...
            "FontSize", opts.legend_font_size);

    end

    %% Bottom row: Hilbert-amplitude metric

    ax_hilbert = nexttile(Tz, i_grid + 3);
    zscore_axes(i_grid + 3) = ax_hilbert;

    hold(ax_hilbert, "on");

    plot_percentile_band( ...
        ax_hilbert, ...
        age_output, ...
        R.hilbert_control_z.lower, ...
        R.hilbert_control_z.upper, ...
        control_colour, ...
        0.16);

    plot_percentile_band( ...
        ax_hilbert, ...
        age_output, ...
        R.hilbert_EPICA_z.lower, ...
        R.hilbert_EPICA_z.upper, ...
        epica_colour, ...
        0.16);

    plot( ...
        ax_hilbert, ...
        age_output, ...
        R.hilbert_control_z.mean, ...
        "Color", control_colour, ...
        "LineWidth", opts.line_width);

    plot( ...
        ax_hilbert, ...
        age_output, ...
        R.hilbert_EPICA_z.mean, ...
        "Color", epica_colour, ...
        "LineWidth", opts.line_width);

    xlabel(ax_hilbert, "Age BP (kyr)");

    style_axis(ax_hilbert, opts);

    add_panel_label( ...
        ax_hilbert, ...
        char('d' + i_grid - 1), ...
        opts);

    if i_grid == 1

        ylabel( ...
            ax_hilbert, ...
            "Hilbert-amplitude mMCV (z-score)");

    end

end

linkaxes(zscore_axes, "x");
linkaxes(zscore_axes(1:3), "y");
linkaxes(zscore_axes(4:6), "y");

for i_axis = 1:numel(zscore_axes)

    xlim( ...
        zscore_axes(i_axis), ...
        [age_output(1), age_output(end)]);

end

sgtitle( ...
    fig_zscore, ...
    sprintf( ...
    "", ...
    opts.n_realizations), ...
    "FontName", opts.font_name, ...
    "FontSize", opts.title_font_size + 1, ...
    "FontWeight", "bold", ...
    "Color", [0.35, 0.35, 0.35]);


% 13. FIGURE 2: PERCENTAGE BIAS


fig_percentage = figure( ...
    "Color", "w", ...
    "Units", "pixels", ...
    "Position", [30, 30, 1600, 900], ...
    "Renderer", "painters");

Tp = tiledlayout( ...
    fig_percentage, ...
    2, ...
    3, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

percentage_axes = gobjects(6, 1);

for i_grid = 1:n_grid

    R = RESULTS{i_grid};
    bias_colour = bias_colours(i_grid, :);

    %% Top row: Thirumalai-style bias

    ax_thir_percent = nexttile(Tp, i_grid);
    percentage_axes(i_grid) = ax_thir_percent;

    hold(ax_thir_percent, "on");

    plot_percentile_band( ...
        ax_thir_percent, ...
        age_output, ...
        R.thir_percent_bias.lower, ...
        R.thir_percent_bias.upper, ...
        bias_colour, ...
        0.18);

    plot( ...
        ax_thir_percent, ...
        age_output, ...
        R.thir_percent_bias.mean, ...
        "Color", bias_colour, ...
        "LineWidth", opts.line_width);

    yline( ...
        ax_thir_percent, ...
        0, ...
        "--", ...
        "Color", [0.25, 0.25, 0.25], ...
        "LineWidth", 1.0);

    title( ...
        ax_thir_percent, ...
        sprintf("%d-year grid", R.grid_years));

    style_axis(ax_thir_percent, opts);

    ax_thir_percent.XTickLabel = [];

    add_panel_label( ...
        ax_thir_percent, ...
        char('a' + i_grid - 1), ...
        opts);

    if i_grid == 1

        ylabel( ...
            ax_thir_percent, ...
            "Thirumalai-style bias (%)");

    end

    %% Bottom row: Hilbert-amplitude bias

    ax_hilbert_percent = nexttile(Tp, i_grid + 3);
    percentage_axes(i_grid + 3) = ax_hilbert_percent;

    hold(ax_hilbert_percent, "on");

    plot_percentile_band( ...
        ax_hilbert_percent, ...
        age_output, ...
        R.hilbert_percent_bias.lower, ...
        R.hilbert_percent_bias.upper, ...
        bias_colour, ...
        0.18);

    plot( ...
        ax_hilbert_percent, ...
        age_output, ...
        R.hilbert_percent_bias.mean, ...
        "Color", bias_colour, ...
        "LineWidth", opts.line_width);

    yline( ...
        ax_hilbert_percent, ...
        0, ...
        "--", ...
        "Color", [0.25, 0.25, 0.25], ...
        "LineWidth", 1.0);

    xlabel(ax_hilbert_percent, "Age BP (kyr)");

    style_axis(ax_hilbert_percent, opts);

    add_panel_label( ...
        ax_hilbert_percent, ...
        char('d' + i_grid - 1), ...
        opts);

    if i_grid == 1

        ylabel( ...
            ax_hilbert_percent, ...
            "Hilbert-amplitude bias (%)");

    end

end

linkaxes(percentage_axes, "x");
linkaxes(percentage_axes(1:3), "y");
linkaxes(percentage_axes(4:6), "y");

for i_axis = 1:numel(percentage_axes)

    xlim( ...
        percentage_axes(i_axis), ...
        [age_output(1), age_output(end)]);

end

sgtitle( ...
    fig_percentage, ...
    sprintf( ...
    "", ...
    opts.n_realizations), ...
    "FontName", opts.font_name, ...
    "FontSize", opts.title_font_size + 1, ...
    "FontWeight", "bold", ...
    "Color", [0.35, 0.35, 0.35]);

fprintf("\nFigures created. No files were saved or exported.\n");






%% ================================================================
% FIGURE 3: 500-YEAR GRID SUMMARY
% ================================================================

R = RESULTS{2};      % 500-year grid
age = age_output;

fig = figure( ...
    "Color","w", ...
    "Units","pixels", ...
    "Position",[80 80 1350 900], ...
    "Renderer","painters");

TL = tiledlayout(2,2,...
    "TileSpacing","compact",...
    "Padding","compact");

%% -----------------------------------------------------------------
% (a) Hilbert
% -----------------------------------------------------------------

ax1 = nexttile;
hold on

plot_percentile_band( ...
    ax1,age,...
    R.hilbert_control_z.lower,...
    R.hilbert_control_z.upper,...
    control_colour,0.16);

plot_percentile_band( ...
    ax1,age,...
    R.hilbert_EPICA_z.lower,...
    R.hilbert_EPICA_z.upper,...
    epica_colour,0.16);

h1=plot(age,...
    R.hilbert_control_z.mean,...
    "Color",control_colour,...
    "LineWidth",opts.line_width);

h2=plot(age,...
    R.hilbert_EPICA_z.mean,...
    "Color",epica_colour,...
    "LineWidth",opts.line_width);

ylabel("Hilbert mMCV (z-score)")

title("Hilbert-amplitude metric")

legend([h1 h2],...
    {"Uniform control","EPICA sampling"},...
    "Location","northwest",...
    "Box","off",...
    "FontName",opts.font_name,...
    "FontSize",opts.legend_font_size);

style_axis(ax1,opts)

ax1.XTickLabel=[];

add_panel_label(ax1,'a',opts)

%% -----------------------------------------------------------------
% (b) Hilbert bias
% -----------------------------------------------------------------

ax2 = nexttile;
hold on

plot_percentile_band( ...
    ax2,...
    age,...
    R.hilbert_percent_bias.lower,...
    R.hilbert_percent_bias.upper,...
    epica_colour,...
    0.18);

plot(age,...
    R.hilbert_percent_bias.mean,...
    "Color",epica_colour,...
    "LineWidth",opts.line_width);

yline(0,'--',...
    "Color",[0.25 0.25 0.25],...
    "LineWidth",1);

ylabel("Bias (%)")

title("Hilbert-amplitude bias")

style_axis(ax2,opts)

ax2.XTickLabel=[];

add_panel_label(ax2,'b',opts)

%% -----------------------------------------------------------------
% (c) Thirumalai
% -----------------------------------------------------------------

ax3 = nexttile;
hold on

plot_percentile_band( ...
    ax3,...
    age,...
    R.thir_control_z.lower,...
    R.thir_control_z.upper,...
    control_colour,...
    0.16);

plot_percentile_band( ...
    ax3,...
    age,...
    R.thir_EPICA_z.lower,...
    R.thir_EPICA_z.upper,...
    epica_colour,...
    0.16);

plot(age,...
    R.thir_control_z.mean,...
    "Color",control_colour,...
    "LineWidth",opts.line_width);

plot(age,...
    R.thir_EPICA_z.mean,...
    "Color",epica_colour,...
    "LineWidth",opts.line_width);

xlabel("Age BP (kyr)")
ylabel("Thirumalai mMCV (z-score)")

title("Thirumalai-style metric")

style_axis(ax3,opts)

add_panel_label(ax3,'c',opts)

%% -----------------------------------------------------------------
% (d) Thirumalai bias
% -----------------------------------------------------------------

ax4 = nexttile;
hold on

plot_percentile_band( ...
    ax4,...
    age,...
    R.thir_percent_bias.lower,...
    R.thir_percent_bias.upper,...
    epica_colour,...
    0.18);

plot(age,...
    R.thir_percent_bias.mean,...
    "Color",epica_colour,...
    "LineWidth",opts.line_width);

yline(0,'--',...
    "Color",[0.25 0.25 0.25],...
    "LineWidth",1);

xlabel("Age BP (kyr)")
ylabel("Bias (%)")

title("Thirumalai-style bias")

style_axis(ax4,opts)

add_panel_label(ax4,'d',opts)

%% -----------------------------------------------------------------
% Common formatting
% -----------------------------------------------------------------

AX=[ax1 ax2 ax3 ax4];

linkaxes(AX,'x');

for k=1:numel(AX)

    xlim(AX(k),[age(1) age(end)])

end

linkaxes([ax1 ax3],'y')
linkaxes([ax2 ax4],'y')

sgtitle( ...
    "",...
    "FontName",opts.font_name,...
    "FontWeight","bold",...
    "FontSize",opts.title_font_size+2,...
    "Color",[0.35 0.35 0.35]);


% LOCAL FUNCTIONS


function [age, proxy] = read_epica_record( ...
    filename, age_min_kyr, age_max_kyr)

    if ~isfile(filename)

        error("EPICA input file not found: %s", filename);

    end

    raw = readmatrix(filename);

    if size(raw, 2) < 2

        error( ...
            "The EPICA file must contain age and proxy values " + ...
            "in its first two columns.");

    end

    age = raw(:, 1);
    proxy = raw(:, 2);

    valid = ...
        isfinite(age) ...
        & isfinite(proxy);

    age = age(valid);
    proxy = proxy(valid);

    % Convert years to kyr when necessary.
    if max(age, [], "omitnan") > 5000

        age = age / 1000;

    end

    [age, order] = sort(age, "ascend");
    proxy = proxy(order);

    [age, unique_indices] = unique(age, "stable");
    proxy = proxy(unique_indices);

    keep = ...
        age >= age_min_kyr ...
        & age <= age_max_kyr;

    age = age(keep);
    proxy = proxy(keep);

    if numel(age) < 100

        error("Too few valid EPICA observations remain.");

    end

end

function metric = thirumalai_metric_raw( ...
    signal, dt_kyr, opts)

    signal = ensure_column_matrix(signal);

    sampling_frequency = 1 / dt_kyr;
    nyquist_frequency = sampling_frequency / 2;

    highpass_frequency = ...
        1 / opts.thirumalai_cutoff_kyr;

    if highpass_frequency >= nyquist_frequency

        error( ...
            "The <10-kyr high-pass cutoff exceeds Nyquist.");

    end

    [b, a] = butter( ...
        opts.filter_order, ...
        highpass_frequency / nyquist_frequency, ...
        "high");

    npad = calculate_padding_points( ...
        dt_kyr, ...
        opts.pad_kyr, ...
        a, ...
        b);

    padded_signal = mirror_pad_matrix( ...
        signal, ...
        npad);

    filtered_padded = filtfilt( ...
        b, ...
        a, ...
        padded_signal);

    % Number of samples corresponding as closely as possible to a
    % centred 2-kyr rolling window.
    rolling_window_points = max( ...
        3, ...
        round(opts.rolling_window_kyr / dt_kyr) + 1);

    effective_span_kyr = ...
        (rolling_window_points - 1) * dt_kyr;

    persistent printed_grids

    grid_key = ...
        sprintf("g%d", round(1000 * dt_kyr));

    if isempty(printed_grids) ...
            || ~isfield(printed_grids, grid_key)

        fprintf( ...
            "%d-year grid: Thirumalai window = %d points; ", ...
            round(1000 * dt_kyr), ...
            rolling_window_points);

        fprintf( ...
            "effective span = %.2f kyr\n", ...
            effective_span_kyr);

        if isempty(printed_grids)

            printed_grids = struct();

        end

        printed_grids.(grid_key) = true;

    end

    metric_padded = movstd( ...
        filtered_padded, ...
        rolling_window_points, ...
        0, ...
        1, ...
        "omitnan", ...
        "Endpoints", ...
        "shrink");

    n = size(signal, 1);

    metric = metric_padded( ...
        npad + 1:npad + n, :);

end

function amplitude = hilbert_metric_raw( ...
    signal, dt_kyr, opts)

    signal = ensure_column_matrix(signal);

    sampling_frequency = 1 / dt_kyr;
    nyquist_frequency = sampling_frequency / 2;

    frequency_band = [ ...
        1 / opts.hilbert_upper_period_kyr, ...
        1 / opts.hilbert_lower_period_kyr];

    normalised_band = ...
        frequency_band / nyquist_frequency;

    if normalised_band(1) <= 0 ...
            || normalised_band(2) >= 1

        error( ...
            "The 2--10 kyr band cannot be represented for dt = %.3f kyr.", ...
            dt_kyr);

    end

    [b, a] = butter( ...
        opts.filter_order, ...
        normalised_band, ...
        "bandpass");

    npad = calculate_padding_points( ...
        dt_kyr, ...
        opts.pad_kyr, ...
        a, ...
        b);

    padded_signal = mirror_pad_matrix( ...
        signal, ...
        npad);

    filtered_padded = filtfilt( ...
        b, ...
        a, ...
        padded_signal);

    amplitude_padded = abs( ...
        hilbert(filtered_padded));

    n = size(signal, 1);

    amplitude = amplitude_padded( ...
        npad + 1:npad + n, :);

end

function npad = calculate_padding_points( ...
    dt_kyr, pad_kyr, a, b)

    requested_padding = ...
        round(pad_kyr / dt_kyr);

    minimum_filter_padding = ...
        3 * max(length(a), length(b));

    npad = max( ...
        requested_padding, ...
        minimum_filter_padding);

end

function padded_signal = mirror_pad_matrix( ...
    signal, npad)

    signal = ensure_column_matrix(signal);

    n = size(signal, 1);

    if npad >= n

        error( ...
            "Mirror padding must be shorter than the input series.");

    end

    left_padding = ...
        signal(npad + 1:-1:2, :);

    right_padding = ...
        signal(n - 1:-1:n - npad, :);

    padded_signal = [ ...
        left_padding; ...
        signal; ...
        right_padding];

end

function [control_z, EPICA_z] = joint_zscore_pair( ...
    control_metric, EPICA_metric)

    control_metric = ...
        ensure_column_matrix(control_metric);

    EPICA_metric = ...
        ensure_column_matrix(EPICA_metric);

    combined_metric = [ ...
        control_metric; ...
        EPICA_metric];

    common_mean = mean( ...
        combined_metric, ...
        1, ...
        "omitnan");

    common_sigma = std( ...
        combined_metric, ...
        0, ...
        1, ...
        "omitnan");

    common_sigma( ...
        ~isfinite(common_sigma) ...
        | common_sigma <= eps) = 1;

    control_z = ...
        (control_metric - common_mean) ...
        ./ common_sigma;

    EPICA_z = ...
        (EPICA_metric - common_mean) ...
        ./ common_sigma;

end

function bias_percent = calculate_percentage_bias( ...
    control_metric, EPICA_metric)

    control_metric = ...
        ensure_column_matrix(control_metric);

    EPICA_metric = ...
        ensure_column_matrix(EPICA_metric);

    denominator = control_metric;

    % Protect against division by a very small value.
    minimum_denominator = ...
        1e-8 .* median( ...
        abs(control_metric), ...
        1, ...
        "omitnan");

    minimum_denominator( ...
        ~isfinite(minimum_denominator) ...
        | minimum_denominator <= eps) = eps;

    for i_column = 1:size(denominator, 2)

        too_small = ...
            abs(denominator(:, i_column)) ...
            < minimum_denominator(i_column);

        denominator(too_small, i_column) = ...
            minimum_denominator(i_column);

    end

    bias_percent = ...
        100 .* ...
        (EPICA_metric - control_metric) ...
        ./ denominator;

end

function smoothed = gaussian_smooth_matrix( ...
    signal, dt_kyr, window_kyr)

    signal = ensure_column_matrix(signal);

    window_points = max( ...
        3, ...
        round(window_kyr / dt_kyr));

    if mod(window_points, 2) == 0

        window_points = ...
            window_points + 1;

    end

    half_window = floor( ...
        window_points / 2);

    kernel_axis = ...
        (-half_window:half_window)';

    % This represents a Gaussian kernel contained within a total
    % window of approximately window_kyr.
    sigma_points = max( ...
        window_points / 6, ...
        1);

    kernel = exp( ...
        -0.5 .* ...
        (kernel_axis ./ sigma_points).^2);

    kernel = ...
        kernel ./ sum(kernel);

    valid = isfinite(signal);

    signal_zero = signal;
    signal_zero(~valid) = 0;

    numerator = conv2( ...
        signal_zero, ...
        kernel, ...
        "same");

    denominator = conv2( ...
        double(valid), ...
        kernel, ...
        "same");

    smoothed = ...
        numerator ./ max(denominator, eps);

    smoothed(denominator <= eps) = NaN;

end

function output = standardise_to_sigma( ...
    signal, target_sigma)

    signal = ensure_column_matrix(signal);

    % Centre each synthetic realisation separately.
    signal = signal - mean( ...
        signal, ...
        1, ...
        "omitnan");

    % Calculate the sample SD of each realisation.
    current_sigma = std( ...
        signal, ...
        0, ...
        1, ...
        "omitnan");

    current_sigma( ...
        ~isfinite(current_sigma) ...
        | current_sigma <= eps) = 1;

    % Give every realisation exactly the same target SD.
    output = ...
        signal ./ current_sigma ...
        .* target_sigma;

end

function signal = ensure_column_matrix(signal)

    if isvector(signal)

        signal = signal(:);

    end

end

function S = ensemble_mean_and_range( ...
    curves, lower_percentile, upper_percentile)

    curves = double(curves);

    S.mean = mean( ...
        curves, ...
        2, ...
        "omitnan");

    S.lower = prctile( ...
        curves, ...
        lower_percentile, ...
        2);

    S.upper = prctile( ...
        curves, ...
        upper_percentile, ...
        2);

end

function plot_percentile_band( ...
    ax, x, lower, upper, colour, alpha_value)

    x = x(:);
    lower = lower(:);
    upper = upper(:);

    valid = ...
        isfinite(x) ...
        & isfinite(lower) ...
        & isfinite(upper);

    fill( ...
        ax, ...
        [x(valid); flipud(x(valid))], ...
        [lower(valid); flipud(upper(valid))], ...
        colour, ...
        "FaceAlpha", alpha_value, ...
        "EdgeColor", "none", ...
        "HandleVisibility", "off");

end

function style_axis(ax, opts)

    set( ...
        ax, ...
        "FontName", opts.font_name, ...
        "FontSize", opts.axis_font_size, ...
        "LineWidth", 0.90, ...
        "TickDir", "out", ...
        "Box", "off", ...
        "Layer", "bottom", ...
        "Color", opts.background_colour, ...
        "XColor", [0, 0, 0], ...
        "YColor", [0, 0, 0]);

    grid(ax, "off");

    ax.XGrid = "on";
    ax.YGrid = "off";

    ax.GridColor = opts.grid_colour;
    ax.GridAlpha = opts.grid_alpha;
    ax.GridLineStyle = "-";

    ax.Title.FontName = opts.font_name;
    ax.Title.FontSize = opts.title_font_size;
    ax.Title.FontWeight = "bold";
    ax.Title.Color = [0.35, 0.35, 0.35];

    ax.XLabel.FontName = opts.font_name;
    ax.XLabel.FontSize = opts.label_font_size;
    ax.XLabel.Color = [0, 0, 0];

    ax.YLabel.FontName = opts.font_name;
    ax.YLabel.FontSize = opts.label_font_size;
    ax.YLabel.Color = [0, 0, 0];

end

function add_panel_label(ax, letter, opts)

    text( ...
        ax, ...
        0.018, ...
        0.95, ...
        sprintf("(%s)", letter), ...
        "Units", "normalized", ...
        "FontName", opts.font_name, ...
        "FontSize", opts.panel_font_size, ...
        "FontWeight", "bold", ...
        "HorizontalAlignment", "left", ...
        "VerticalAlignment", "top", ...
        "Color", [0, 0, 0], ...
        "Clipping", "off");

end