
% CURVED-TREND NOISE-SENSITIVITY TEST
%
% ONE TREND ONLY:h
% flat before 600 kyr BP, then a gently curved accelerating
% increase towards the present.
%
% Noise levels:
% signal:noise = 1:0, 1:0.2, 1:0.5, 1:1.0, 1:1.5
%
% 100 Monte Carlo realisations per noise level.
%
% Requires:
%   chpttests.m
%   original Abram/Marron SiZer folder
%   BEAST installed
%


clear;
close all;
clc;

rng(1);


% 1. SETTINGS

dt = 0.5;

age_max = 800;

age = ...
    (0:dt:age_max)';


change_age = 600;


sigma_proxy = ...
    0.88047;


phi_proxy = ...
    0.93004;


deltaT = ...
    2 * sigma_proxy;


% Definition:
%
% deltaT : 2*sigma_noise = 1 : noise_ratio

noise_ratios = ...
    [ ...
    0 ...
    0.2 ...
    0.5 ...
    1.0 ...
    1.5 ...
    ];


nNoise = ...
    numel( ...
    noise_ratios);


nRep = ...
    1000;


burnin = ...
    2000;




% 2. ONE CLEAN CURVED TREND ONLY
%
% Flat between 800 and 600 kyr BP.
%
% From 600 kyr BP towards the present:
% gently curved accelerating increase.


clean_trend = ...
    zeros( ...
    size(age));


idx_post = ...
    age <= ...
    change_age;


u = ...
    ( ...
    change_age - ...
    age(idx_post) ...
    ) / ...
    change_age;


% u = 0 at 600 kyr BP
%
% u = 1 at 0 kyr BP


clean_trend(idx_post) = ...
    deltaT * ...
    ( ...
    1 - ...
    cos( ...
    (pi/2) * ...
    u) ...
    );




% 3. EXACT SIZER AND FINDCHANGEPTS SETTINGS


opts = ...
    struct();


opts.methods = ...
    [ ...
    "sizer" ...
    "findchangepts" ...
    ];




% SIZER


opts.sizer.bandwidth_min = ...
    60;


opts.sizer.bandwidth_max = ...
    100;


opts.sizer.n_bandwidths = ...
    41;


opts.sizer.x_step = ...
    1.0;


opts.sizer.alpha = ...
    0.10;


opts.sizer.simflag = ...
    2;


opts.sizer.iregtdist = ...
    0;


opts.sizer.endpoint_flag = ...
    0;


opts.sizer.boundary_adjustment = ...
    0;


opts.sizer.onset_mode = ...
    "all";


opts.sizer.min_run_kyr = ...
    40;


opts.sizer.edge_ignore_kyr = ...
    0;


opts.sizer.cluster_gap_kyr = ...
    35;


opts.sizer.min_bw_fraction = ...
    0.80;


opts.sizer.uncertainty_mode = ...
    "iqr";




% FINDCHANGEPTS


opts.findchangepts.smooth_kyr = ...
    0;


opts.findchangepts.max_num_changes = ...
    1;




% 4. BEAST SETTINGS


if ...
        exist( ...
        'beast', ...
        'file') ~= ...
        2


    error( ...
        'BEAST was not found on the MATLAB path.');


end


beast_tcp_minmax = ...
    [0 1];


beast_torder_minmax = ...
    [0 1];


beast_mcmc_samples = ...
    4000;


beast_mcmc_burnin = ...
    1000;


beast_mcmc_chains = ...
    2;


beast_mcmc_thin = ...
    5;




% 5. GENERATE THE SAME 100 BASE AR(1) REALISATIONS
%
% The same AR(1) noise patterns are used at all noise levels.
%
% Only their amplitude changes.

n = ...
    numel(age);


base_noise = ...
    nan( ...
    n, ...
    nRep);


for r = 1:nRep


    noise_long = ...
        zeros( ...
        n + ...
        burnin, ...
        1);


    for k = 2:(n + burnin)


        noise_long(k) = ...
            phi_proxy * ...
            noise_long(k-1) + ...
            randn;


    end


    noise_raw = ...
        noise_long( ...
        burnin+1:end);


    base_noise(:,r) = ...
        ( ...
        noise_raw - ...
        mean( ...
        noise_raw, ...
        'omitnan') ...
        ) ./ ...
        std( ...
        noise_raw, ...
        'omitnan');


end




% 6. STORAGE


cp_sizer = ...
    nan( ...
    nRep, ...
    nNoise);


cp_find = ...
    nan( ...
    nRep, ...
    nNoise);


cp_beast = ...
    nan( ...
    nRep, ...
    nNoise);



sizer_success = ...
    false( ...
    nRep, ...
    nNoise);


find_success = ...
    false( ...
    nRep, ...
    nNoise);


beast_success = ...
    false( ...
    nRep, ...
    nNoise);



beast_ncp_mode = ...
    nan( ...
    nRep, ...
    nNoise);



example_series = ...
    nan( ...
    n, ...
    nNoise);




% 7. MONTE CARLO LOOP

fprintf( ...
    '\nCURVED-TREND NOISE-SENSITIVITY TEST\n');


fprintf( ...
    'True onset = %.1f kyr BP\n', ...
    change_age);


fprintf( ...
    'AR(1) phi = %.6f\n', ...
    phi_proxy);


fprintf( ...
    'Realisations = %d per noise level\n\n', ...
    nRep);



for q = 1:nNoise


    ratio = ...
        noise_ratios(q);


    sigma_noise = ...
        ratio * ...
        deltaT / ...
        2;


    fprintf( ...
        'Signal:noise = 1:%.1f\n', ...
        ratio);



    for r = 1:nRep



        
        % SYNTHETIC SERIES
       

        noise = ...
            sigma_noise * ...
            base_noise(:,r);


        synthetic_raw = ...
            clean_trend + ...
            noise;


        synthetic_z = ...
            ( ...
            synthetic_raw - ...
            mean( ...
            synthetic_raw, ...
            'omitnan') ...
            ) ./ ...
            std( ...
            synthetic_raw, ...
            'omitnan');


        if r == 1


            example_series(:,q) = ...
                synthetic_raw;


        end



        
        % SIZER + FINDCHANGEPTS
        

        out = ...
            chpttests( ...
            age, ...
            synthetic_z, ...
            opts);



        cp_sizer(r,q) = ...
            out.sizer.cp_age;


        cp_find(r,q) = ...
            out.findchangepts.cp_age;



        sizer_success(r,q) = ...
            out.sizer.run_successful;


        find_success(r,q) = ...
            out.findchangepts.run_successful;



        
        % BEAST
        

        try


            beast_seed = ...
                ( ...
                q - ...
                1 ...
                ) * ...
                nRep + ...
                r;



            [ ...
                cp_beast(r,q), ...
                beast_ncp_mode(r,q) ...
                ] = ...
                run_beast_once( ...
                synthetic_z, ...
                age, ...
                dt, ...
                age_max, ...
                beast_tcp_minmax, ...
                beast_torder_minmax, ...
                beast_seed, ...
                beast_mcmc_samples, ...
                beast_mcmc_burnin, ...
                beast_mcmc_chains, ...
                beast_mcmc_thin);



            beast_success(r,q) = ...
                true;



        catch ME


            if r == 1


                fprintf( ...
                    'BEAST error: %s\n', ...
                    ME.message);


            end


        end



       
        % PROGRESS
        

        if ...
                mod( ...
                r, ...
                10) == ...
                0


            fprintf( ...
                '  %d / %d\n', ...
                r, ...
                nRep);


        end


    end


end


fprintf( ...
    '\nAll calculations completed.\n');




% 8. SUMMARY TABLE


method_names = ...
    [ ...
    "SiZer"
    "findchangepts"
    "BEAST"
    ];


NoiseRatio = ...
    [];


NoiseCondition = ...
    strings( ...
    0, ...
    1);


Method = ...
    strings( ...
    0, ...
    1);


SuccessfulRuns = ...
    [];


DetectionRate_pct = ...
    [];


MedianAge_kyr = ...
    [];


Q25_kyr = ...
    [];


Q75_kyr = ...
    [];


P05_kyr = ...
    [];


P95_kyr = ...
    [];


MedianError_kyr = ...
    [];



for q = 1:nNoise


    cp_all = {

        cp_sizer(:,q)

        cp_find(:,q)

        cp_beast(:,q)

        };


    success_all = {

        sizer_success(:,q)

        find_success(:,q)

        beast_success(:,q)

        };



    for m = 1:3


        cp = ...
            cp_all{m};


        cp = ...
            cp( ...
            isfinite(cp));



        NoiseRatio( ...
            end+1, ...
            1) = ...
            noise_ratios(q);



        NoiseCondition( ...
            end+1, ...
            1) = ...
            "1:" + ...
            string( ...
            noise_ratios(q));



        Method( ...
            end+1, ...
            1) = ...
            method_names(m);



        SuccessfulRuns( ...
            end+1, ...
            1) = ...
            sum( ...
            success_all{m});



        DetectionRate_pct( ...
            end+1, ...
            1) = ...
            100 * ...
            numel(cp) / ...
            nRep;



        if isempty(cp)


            MedianAge_kyr( ...
                end+1, ...
                1) = ...
                NaN;


            Q25_kyr( ...
                end+1, ...
                1) = ...
                NaN;


            Q75_kyr( ...
                end+1, ...
                1) = ...
                NaN;


            P05_kyr( ...
                end+1, ...
                1) = ...
                NaN;


            P95_kyr( ...
                end+1, ...
                1) = ...
                NaN;


            MedianError_kyr( ...
                end+1, ...
                1) = ...
                NaN;



        else


            MedianAge_kyr( ...
                end+1, ...
                1) = ...
                median( ...
                cp, ...
                'omitnan');


            Q25_kyr( ...
                end+1, ...
                1) = ...
                prctile( ...
                cp, ...
                25);


            Q75_kyr( ...
                end+1, ...
                1) = ...
                prctile( ...
                cp, ...
                75);


            P05_kyr( ...
                end+1, ...
                1) = ...
                prctile( ...
                cp, ...
                5);


            P95_kyr( ...
                end+1, ...
                1) = ...
                prctile( ...
                cp, ...
                95);


            MedianError_kyr( ...
                end+1, ...
                1) = ...
                median( ...
                cp - ...
                change_age, ...
                'omitnan');


        end


    end


end



Summary = ...
    table( ...
    NoiseRatio, ...
    NoiseCondition, ...
    Method, ...
    SuccessfulRuns, ...
    DetectionRate_pct, ...
    MedianAge_kyr, ...
    Q25_kyr, ...
    Q75_kyr, ...
    P05_kyr, ...
    P95_kyr, ...
    MedianError_kyr);



disp(' ');


disp( ...
    Summary);




% 9. BEAST 0-CP / 1-CP SUMMARY


fprintf( ...
    '\nBEAST MODEL-SELECTION SUMMARY\n');



for q = 1:nNoise


    valid = ...
        beast_success(:,q) & ...
        isfinite( ...
        beast_ncp_mode(:,q));


    nValid = ...
        sum(valid);



    if nValid == 0


        fprintf( ...
            '1:%.1f -> no valid BEAST runs\n', ...
            noise_ratios(q));



    else


        pct0 = ...
            100 * ...
            sum( ...
            beast_ncp_mode(valid,q) == ...
            0 ...
            ) / ...
            nValid;



        pct1 = ...
            100 * ...
            sum( ...
            beast_ncp_mode(valid,q) >= ...
            1 ...
            ) / ...
            nValid;



        fprintf( ...
            '1:%.1f -> 0 CP = %.1f%%; 1 CP = %.1f%%\n', ...
            noise_ratios(q), ...
            pct0, ...
            pct1);


    end


end




% 10. FIGURE SETTINGS


font_name = ...
    'Cambria Math';


col_sizer = ...
    [ ...
    0.05 ...
    0.15 ...
    0.95 ...
    ];


col_find = ...
    [ ...
    1.00 ...
    0.45 ...
    0.00 ...
    ];


col_beast = ...
    [ ...
    0.72 ...
    0.00 ...
    0.88 ...
    ];



all_error = [

    cp_sizer(:) - ...
    change_age

    cp_find(:) - ...
    change_age

    cp_beast(:) - ...
    change_age

    ];


all_error = ...
    all_error( ...
    isfinite( ...
    all_error));



if isempty( ...
        all_error)


    error_limit = ...
        100;



else


    error_limit = ...
        max( ...
        50, ...
        25 * ...
        ceil( ...
        prctile( ...
        abs( ...
        all_error), ...
        95) / ...
        25));


end


error_limit = ...
    min( ...
    error_limit, ...
    400);




% 11. FIGURE


fig = figure( ...
    'Color', ...
    'w', ...
    'Units', ...
    'pixels', ...
    'Position', ...
    [50 40 1250 760], ...
    'Renderer', ...
    'painters');

left_margin = 0.065;
right_margin = 0.025;
top_margin = 0.075;
bottom_margin = 0.085;

row_gap = 0.010;
column_gap = 0.014;

column_widths = [0.40 0.18 0.18 0.18];

usable_width = ...
    1 - left_margin - right_margin - ...
    3 * column_gap;

column_widths = ...
    column_widths / sum(column_widths) * ...
    usable_width;

x0 = nan(1,4);
x0(1) = left_margin;

for c = 2:4
    x0(c) = ...
        x0(c-1) + ...
        column_widths(c-1) + ...
        column_gap;
end

panel_height = ...
    (1 - top_margin - bottom_margin - ...
    (nNoise - 1) * row_gap) / ...
    nNoise;

% Common y limits for all synthetic-example panels
all_example = [
    example_series(:)
    clean_trend(:)
    ];

all_example = ...
    all_example(isfinite(all_example));

y_min = min(all_example);
y_max = max(all_example);

y_pad = 0.06 * (y_max - y_min);

if y_pad == 0
    y_pad = 1;
end

example_ylim = ...
    [y_min - y_pad, y_max + y_pad];

for q = 1:nNoise

    y0 = ...
        1 - top_margin - ...
        q * panel_height - ...
        (q - 1) * row_gap;

    
    % SYNTHETIC EXAMPLE
  

    ax1 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(1), y0, column_widths(1), panel_height]);

    plot( ...
        ax1, ...
        age, ...
        example_series(:,q), ...
        'Color', ...
        [0.65 0.65 0.65], ...
        'LineWidth', ...
        0.55);

    hold(ax1, 'on');

    plot( ...
        ax1, ...
        age, ...
        clean_trend, ...
        'k-', ...
        'LineWidth', ...
        1.8);

    xline( ...
        ax1, ...
        change_age, ...
        '--', ...
        'Color', ...
        [0.35 0.35 0.35], ...
        'LineWidth', ...
        1.0);

    set( ...
        ax1, ...
        'XDir', ...
        'reverse', ...
        'XLim', ...
        [0 age_max], ...
        'YLim', ...
        example_ylim, ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        8, ...
        'LineWidth', ...
        0.7, ...
        'TickDir', ...
        'out', ...
        'Box', ...
        'on', ...
        'Color', ...
        [0.95 0.92 0.94], ...
        'XGrid', ...
        'on', ...
        'YGrid', ...
        'on', ...
        'GridColor', ...
        [1 1 1], ...
        'GridAlpha', ...
        1.0, ...
        'GridLineStyle', ...
        '-', ...
        'Layer', ...
        'bottom');

    % Two internal y-axis labels, matching the trend-geometry figure
    y_range = ...
        example_ylim(2) - example_ylim(1);

    ax1.YTick = ...
        [ ...
        example_ylim(1) + 0.25 * y_range, ...
        example_ylim(1) + 0.75 * y_range ...
        ];

    ax1.YTickLabel = ...
        compose( ...
        '%.1f', ...
        ax1.YTick);

    ax1.XTick = ...
        [0 200 400 600 800];

    if q == 1

        title( ...
            ax1, ...
            'Synthetic curved trend', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            10, ...
            'FontName', ...
            font_name);

    end

    % Noise-condition label inside the panel
    text( ...
        ax1, ...
        0.018, ...
        0.82, ...
        sprintf('1:%.1f', noise_ratios(q)), ...
        'Units', ...
        'normalized', ...
        'HorizontalAlignment', ...
        'left', ...
        'VerticalAlignment', ...
        'middle', ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        9, ...
        'FontWeight', ...
        'bold', ...
        'Clipping', ...
        'on');

    if q < nNoise

        ax1.XTickLabel = [];

    else

        xlabel( ...
            ax1, ...
            'Age BP (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            9);

    end

    
    % SIZER
   
    ax2 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(2), y0, column_widths(2), panel_height]);

    draw_distribution( ...
        ax2, ...
        cp_sizer(:,q), ...
        change_age, ...
        nRep, ...
        col_sizer, ...
        error_limit, ...
        font_name);

    if q == 1

        title( ...
            ax2, ...
            'SiZer', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            10, ...
            'FontName', ...
            font_name);

    end

    if q < nNoise

        ax2.XTickLabel = [];

    else

        xlabel( ...
            ax2, ...
            'Detected age - 600 kyr (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            8);

    end

    
    % FINDCHANGEPTS
    

    ax3 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(3), y0, column_widths(3), panel_height]);

    draw_distribution( ...
        ax3, ...
        cp_find(:,q), ...
        change_age, ...
        nRep, ...
        col_find, ...
        error_limit, ...
        font_name);

    if q == 1

        title( ...
            ax3, ...
            'findchangepts', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            10, ...
            'FontName', ...
            font_name);

    end

    if q < nNoise

        ax3.XTickLabel = [];

    else

        xlabel( ...
            ax3, ...
            'Detected age - 600 kyr (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            8);

    end

    
    % BEAST
    

    ax4 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(4), y0, column_widths(4), panel_height]);

    draw_distribution( ...
        ax4, ...
        cp_beast(:,q), ...
        change_age, ...
        nRep, ...
        col_beast, ...
        error_limit, ...
        font_name);

    if q == 1

        title( ...
            ax4, ...
            'BEAST', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            10, ...
            'FontName', ...
            font_name);

    end

    if q < nNoise

        ax4.XTickLabel = [];

    else

        xlabel( ...
            ax4, ...
            'Detected age - 600 kyr (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            8);

    end

end

annotation( ...
    fig, ...
    'textbox', ...
    [0.015 0.965 0.035 0.025], ...
    'String', ...
    'b', ...
    'LineStyle', ...
    'none', ...
    'FontName', ...
    font_name, ...
    'FontSize', ...
    11, ...
    'FontWeight', ...
    'bold');

annotation( ...
    fig, ...
    'textbox', ...
    [0.060 0.960 0.35 0.03], ...
    'String', ...
    'Changepoint tests: curved-trend noise sensitivity', ...
    'LineStyle', ...
    'none', ...
    'FontName', ...
    font_name, ...
    'FontSize', ...
    10, ...
    'FontWeight', ...
    'normal');

fprintf('\nFigure created. No files were saved.\n');

% LOCAL FUNCTION:
% RUN BEAST ONCE

function [ ...
    cp_age, ...
    ncp_mode ...
    ] = ...
    run_beast_once( ...
    y, ...
    age, ...
    dt, ...
    age_max, ...
    tcp_minmax, ...
    torder_minmax, ...
    seed, ...
    mcmc_samples, ...
    mcmc_burnin, ...
    mcmc_chains, ...
    mcmc_thin)


cp_age = ...
    NaN;


ncp_mode = ...
    NaN;



out = ...
    beast( ...
    y(:), ...
    'start', ...
    0, ...
    'deltat', ...
    dt, ...
    'season', ...
    'none', ...
    'tcp.minmax', ...
    tcp_minmax, ...
    'torder.minmax', ...
    torder_minmax, ...
    'mcmc.seed', ...
    seed, ...
    'mcmc.samples', ...
    mcmc_samples, ...
    'mcmc.burnin', ...
    mcmc_burnin, ...
    'mcmc.chains', ...
    mcmc_chains, ...
    'mcmc.thin', ...
    mcmc_thin, ...
    'print.progress', ...
    false, ...
    'print.param', ...
    false, ...
    'print.warning', ...
    false, ...
    'quiet', ...
    true, ...
    'dump.ci', ...
    false);



if ...
        ~isfield( ...
        out, ...
        'trend')


    return;


end




% MODAL NUMBER OF CHANGEPOINTS


if ...
        isfield( ...
        out.trend, ...
        'ncp_mode') && ...
        ~isempty( ...
        out.trend.ncp_mode)


    tmp = ...
        double( ...
        out.trend.ncp_mode(:));


    tmp = ...
        tmp( ...
        isfinite(tmp));


    if ...
            ~isempty(tmp)


        ncp_mode = ...
            tmp(1);


    end


end



if ...
        ~isfinite( ...
        ncp_mode) && ...
        isfield( ...
        out.trend, ...
        'ncpPr') && ...
        ~isempty( ...
        out.trend.ncpPr)


    ncpPr = ...
        double( ...
        out.trend.ncpPr(:));


    [ ...
        ~, ...
        idx_mode ...
        ] = ...
        max( ...
        ncpPr);


    ncp_mode = ...
        idx_mode - ...
        1;


end



% Do not force a changepoint when BEAST selects 0 CP.

if ...
        ~isfinite( ...
        ncp_mode) || ...
        ncp_mode < ...
        1


    return;


end




% PREFERRED CHANGEPOINT EXTRACTION


if ...
        isfield( ...
        out.trend, ...
        'cp') && ...
        ~isempty( ...
        out.trend.cp)


    cp_candidates = ...
        double( ...
        out.trend.cp(:));



    if ...
            isfield( ...
            out.trend, ...
            'cpPr') && ...
            ~isempty( ...
            out.trend.cpPr)


        cp_pr = ...
            double( ...
            out.trend.cpPr(:));


    else


        cp_pr = ...
            nan( ...
            size( ...
            cp_candidates));


    end



    valid = ...
        isfinite( ...
        cp_candidates) & ...
        cp_candidates >= ...
        0 & ...
        cp_candidates <= ...
        age_max;



    if ...
            any(valid)


        cp_candidates = ...
            cp_candidates(valid);



        if ...
                numel(cp_pr) == ...
                numel(valid)


            cp_pr = ...
                cp_pr(valid);


        else


            cp_pr = ...
                nan( ...
                size( ...
                cp_candidates));


        end



        if ...
                any( ...
                isfinite( ...
                cp_pr))


            [ ...
                ~, ...
                best ...
                ] = ...
                max( ...
                cp_pr);


            cp_age = ...
                cp_candidates(best);


        else


            cp_age = ...
                cp_candidates(1);


        end


    end


end




% FALLBACK
%
% Used only when BEAST selected a one-CP model.


if ...
        ~isfinite( ...
        cp_age) && ...
        isfield( ...
        out.trend, ...
        'cpOccPr') && ...
        ~isempty( ...
        out.trend.cpOccPr)


    cp_occ = ...
        double( ...
        out.trend.cpOccPr(:));


    if ...
            numel(cp_occ) == ...
            numel(age)


        [ ...
            ~, ...
            best ...
            ] = ...
            max( ...
            cp_occ);


        cp_age = ...
            age(best);


    end


end


end




% LOCAL FUNCTION:
% DRAW DISTRIBUTION

function draw_distribution( ...
    ax, ...
    cp_age, ...
    true_age, ...
    nRep, ...
    colour, ...
    error_limit, ...
    font_name)

hold(ax, 'on');

xline( ...
    ax, ...
    0, ...
    '--', ...
    'Color', ...
    [0.35 0.35 0.35], ...
    'LineWidth', ...
    0.9);

valid = ...
    cp_age(isfinite(cp_age));

error_age = ...
    valid - true_age;

if isempty(error_age)

    text( ...
        ax, ...
        0.50, ...
        0.58, ...
        'ND', ...
        'Units', ...
        'normalized', ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'middle', ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        9, ...
        'FontWeight', ...
        'bold', ...
        'Color', ...
        colour);

else

    p05 = prctile(error_age, 5);
    p95 = prctile(error_age, 95);
    q25 = prctile(error_age, 25);
    q75 = prctile(error_age, 75);
    med = median(error_age, 'omitnan');

    % 5-95% range
    plot( ...
        ax, ...
        [p05 p95], ...
        [0.56 0.56], ...
        '-', ...
        'Color', ...
        colour, ...
        'LineWidth', ...
        1.0);

    % 25-75% range
    plot( ...
        ax, ...
        [q25 q75], ...
        [0.56 0.56], ...
        '-', ...
        'Color', ...
        colour, ...
        'LineWidth', ...
        3.0);

    % Median
    plot( ...
        ax, ...
        med, ...
        0.56, ...
        's', ...
        'MarkerSize', ...
        8, ...
        'MarkerFaceColor', ...
        'w', ...
        'MarkerEdgeColor', ...
        colour, ...
        'LineWidth', ...
        1.5);

end

detection_rate = ...
    100 * numel(valid) / nRep;

% Detection percentage in the upper-right corner
text( ...
    ax, ...
    0.97, ...
    0.87, ...
    sprintf('%.0f%%', detection_rate), ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'middle', ...
    'FontName', ...
    font_name, ...
    'FontSize', ...
    10, ...
    'FontWeight', ...
    'bold', ...
    'Color', ...
    [0.25 0.25 0.25]);

set( ...
    ax, ...
    'XLim', ...
    [-error_limit error_limit], ...
    'YLim', ...
    [0 1], ...
    'YTick', ...
    [0.25 0.75], ...
    'YTickLabel', ...
    [], ...
    'FontName', ...
    font_name, ...
    'FontSize', ...
    8, ...
    'LineWidth', ...
    0.7, ...
    'TickDir', ...
    'out', ...
    'TickLength', ...
    [0 0], ...
    'XMinorTick', ...
    'off', ...
    'YMinorTick', ...
    'off', ...
    'Box', ...
    'on', ...
    'Color', ...
    [0.90 0.94 0.99], ...
    'XGrid', ...
    'on', ...
    'YGrid', ...
    'on', ...
    'GridColor', ...
    [0.72 0.72 0.72], ...
    'GridAlpha', ...
    0.60, ...
    'GridLineStyle', ...
    '-', ...
    'Layer', ...
    'bottom');

% Internal x-axis labels, away from panel boundaries
ax.XTick = ...
    [ ...
    -0.50 * error_limit, ...
     0, ...
     0.50 * error_limit ...
    ];

ax.XTickLabel = ...
    compose( ...
    '%.0f', ...
    ax.XTick);

end
