clear;
close all;
clc;


%% ============================================================
% EPICA TEMPORAL-RESOLUTION EFFECT TEST
%
% Real EPICA:
%   (a) Original temporal resolution
%   (b) Thirumalai-style mMCV
%   (c) <2 kyr and 2--10 kyr frequency decomposition
%   (d) Thesis Hilbert-amplitude mMCV
%
% Synthetic experiment:
%   (e) Thirumalai-style resolution test
%   (f) Hilbert-amplitude resolution test
%



% 1. SETTINGS
opts.epica_file = "Epica_deuterium.txt";


% Time axis
opts.age_min_kyr = 0;
opts.age_max_kyr = 801;
opts.dt_kyr = 0.1;                  % 100 years
opts.interp_method = "pchip";


% Filtering
opts.filter_order = 4;
opts.thirumalai_cutoff_kyr = 10;    % retain periods <10 kyr
opts.split_period_kyr = 2;          % separate <2 and 2--10 kyr
opts.pad_kyr = 10;


% mMCV and smoothing
opts.rolling_window_kyr = 2;
opts.gaussian_window_kyr = 100;
opts.resolution_smooth_kyr = 20;    % visualisation only


% Monte Carlo
opts.n_realizations = 10000;
opts.chunk_size = 50;
opts.random_seed = 20260713;
opts.burn_in_steps = 2000;
opts.output_dt_kyr = 1.0;
opts.percentiles = [5 95];


% Plot appearance
opts.font_name = "Cambria Math";
opts.axis_font_size = 8.5;
opts.ylabel_font_size = 8.5;
opts.xlabel_font_size = 9;
opts.panel_heading_font_size = 9;
opts.legend_font_size = 7.5;

opts.figure_position = [2 2 18.2 18.5];
% Export
opts.export_figure = true;
opts.output_name = ...
    "EPICA_temporal_resolution_test_6panel";




% 2. READ AND INTERPOLATE THE FULL EPICA RECORD


[age_obs, deltaD_obs] = ...
    read_epica_record( ...
    opts.epica_file, ...
    opts.age_min_kyr, ...
    opts.age_max_kyr);


age_start = ...
    ceil( ...
    max( ...
    opts.age_min_kyr, ...
    min(age_obs)) ...
    / opts.dt_kyr) ...
    * opts.dt_kyr;


age_end = ...
    floor( ...
    min( ...
    opts.age_max_kyr, ...
    max(age_obs)) ...
    / opts.dt_kyr) ...
    * opts.dt_kyr;


age = ...
    ( ...
    age_start : ...
    opts.dt_kyr : ...
    age_end ...
    )';


keep_obs = ...
    age_obs >= age(1) & ...
    age_obs <= age(end);


age_obs = ...
    age_obs(keep_obs);


deltaD_obs = ...
    deltaD_obs(keep_obs);


deltaD_interp = ...
    interp1( ...
    age_obs, ...
    deltaD_obs, ...
    age, ...
    opts.interp_method);


fprintf( ...
    "\nEPICA loaded: %d observations, %.1f--%.1f kyr BP.\n", ...
    numel(age_obs), ...
    age(1), ...
    age(end));




% 3. DESIGN FILTERS


fs = ...
    1 / opts.dt_kyr;


nyquist = ...
    fs / 2;


% High-pass filter retaining periods shorter than 10 kyr

[b_hp10, a_hp10] = ...
    butter( ...
    opts.filter_order, ...
    (1 / opts.thirumalai_cutoff_kyr) ...
    / nyquist, ...
    "high");


% High-pass filter retaining periods shorter than 2 kyr

[b_hp2, a_hp2] = ...
    butter( ...
    opts.filter_order, ...
    (1 / opts.split_period_kyr) ...
    / nyquist, ...
    "high");


% Band-pass filter retaining periods between 2 and 10 kyr

[b_bp2_10, a_bp2_10] = ...
    butter( ...
    opts.filter_order, ...
    [ ...
    1 / opts.thirumalai_cutoff_kyr ...
    1 / opts.split_period_kyr ...
    ] ...
    / nyquist, ...
    "bandpass");


% Mirror-padding length

npad = ...
    round( ...
    opts.pad_kyr ...
    / opts.dt_kyr);


npad = ...
    max( ...
    npad, ...
    3 * max( ...
    [ ...
    length(a_hp10) ...
    length(b_hp10) ...
    length(a_hp2) ...
    length(b_hp2) ...
    length(a_bp2_10) ...
    length(b_bp2_10) ...
    ]));


% Half-width of the centred 2-kyr moving window

half_window_points = ...
    round( ...
    opts.rolling_window_kyr ...
    / ...
    (2 * opts.dt_kyr));




% 4. ESTIMATE EPICA-DERIVED AR(1) PARAMETERS

EPICA = ...
    struct();


% Remove the 100-kyr Gaussian-smoothed long-term component

EPICA.deltaD_long_term = ...
    gaussian_smooth_matrix( ...
    deltaD_interp, ...
    opts.dt_kyr, ...
    opts.gaussian_window_kyr);


EPICA.deltaD_residual = ...
    deltaD_interp ...
    - EPICA.deltaD_long_term;


% Lag-1 autocorrelation

x_previous = ...
    EPICA.deltaD_residual(1:end-1);


x_next = ...
    EPICA.deltaD_residual(2:end);


valid_pair = ...
    isfinite(x_previous) & ...
    isfinite(x_next);


EPICA.phi = ...
    corr( ...
    x_previous(valid_pair), ...
    x_next(valid_pair));


EPICA.phi = ...
    max( ...
    min( ...
    EPICA.phi, ...
    0.999), ...
    -0.999);


% Standard deviation of the detrended EPICA record

EPICA.sigma_residual = ...
    std( ...
    EPICA.deltaD_residual, ...
    0, ...
    "omitnan");


fprintf( ...
    "EPICA AR(1): phi = %.6f, residual SD = %.6f.\n", ...
    EPICA.phi, ...
    EPICA.sigma_residual);




% 5. CALCULATE REAL EPICA mMCV METRICS



% ------------------------------------------------------------
% Thirumalai-style metric:
% <10 kyr high-pass-filtered signal
% + centred 2-kyr rolling standard deviation
% ------------------------------------------------------------

[~, EPICA.mmcv_thirumalai] = ...
    filtered_moving_std_with_padding( ...
    deltaD_interp, ...
    b_hp10, ...
    a_hp10, ...
    npad, ...
    half_window_points);


% ------------------------------------------------------------
% Frequency decomposition of the rolling-SD metric
% ------------------------------------------------------------

[~, EPICA.mmcv_lt2] = ...
    filtered_moving_std_with_padding( ...
    deltaD_interp, ...
    b_hp2, ...
    a_hp2, ...
    npad, ...
    half_window_points);


[~, EPICA.mmcv_2_10_movstd] = ...
    filtered_moving_std_with_padding( ...
    deltaD_interp, ...
    b_bp2_10, ...
    a_bp2_10, ...
    npad, ...
    half_window_points);



% Thesis metric:
% 2--10 kyr Hilbert amplitude


[~, hilbert_amplitude] = ...
    filtered_hilbert_with_padding( ...
    deltaD_interp, ...
    b_bp2_10, ...
    a_bp2_10, ...
    npad);


EPICA.mmcv_hilbert_z = ...
    zscore_columns( ...
    hilbert_amplitude);



% 100-kyr long-term components for visualisation


EPICA.mmcv_thirumalai_smooth = ...
    gaussian_smooth_matrix( ...
    EPICA.mmcv_thirumalai, ...
    opts.dt_kyr, ...
    opts.gaussian_window_kyr);


EPICA.mmcv_lt2_smooth = ...
    gaussian_smooth_matrix( ...
    EPICA.mmcv_lt2, ...
    opts.dt_kyr, ...
    opts.gaussian_window_kyr);


EPICA.mmcv_2_10_movstd_smooth = ...
    gaussian_smooth_matrix( ...
    EPICA.mmcv_2_10_movstd, ...
    opts.dt_kyr, ...
    opts.gaussian_window_kyr);


EPICA.mmcv_hilbert_z_smooth = ...
    gaussian_smooth_matrix( ...
    EPICA.mmcv_hilbert_z, ...
    opts.dt_kyr, ...
    opts.gaussian_window_kyr);




% 6. CALCULATE ORIGINAL EPICA TEMPORAL RESOLUTION


EPICA.sampling_interval_raw = ...
    diff(age_obs);


EPICA.sampling_interval_midpoint = ...
    ( ...
    age_obs(1:end-1) ...
    + age_obs(2:end) ...
    ) ...
    / 2;


% Place observation-spacing estimates on the regular time grid

EPICA.sampling_interval = ...
    interp1( ...
    EPICA.sampling_interval_midpoint, ...
    EPICA.sampling_interval_raw, ...
    age, ...
    "nearest", ...
    "extrap");


% Smooth only for visualisation

EPICA.sampling_interval_smooth = ...
    gaussian_smooth_matrix( ...
    EPICA.sampling_interval, ...
    opts.dt_kyr, ...
    opts.resolution_smooth_kyr);


fprintf( ...
    "Median EPICA spacing = %.0f yr; maximum = %.0f yr.\n", ...
    1000 ...
    * median( ...
    EPICA.sampling_interval_raw, ...
    "omitnan"), ...
    1000 ...
    * max( ...
    EPICA.sampling_interval_raw, ...
    [], ...
    "omitnan"));




% 7. SYNTHETIC RESOLUTION EXPERIMENT


rng( ...
    opts.random_seed, ...
    "twister");


output_stride = ...
    round( ...
    opts.output_dt_kyr ...
    / opts.dt_kyr);


if ...
        abs( ...
        output_stride ...
        * opts.dt_kyr ...
        - opts.output_dt_kyr) ...
        > 1e-10

    error( ...
        [ ...
        "opts.output_dt_kyr must be an integer " ...
        "multiple of opts.dt_kyr." ...
        ]);

end


output_index = ...
    ( ...
    1 : ...
    output_stride : ...
    numel(age) ...
    )';


age_output = ...
    age(output_index);


n_output = ...
    numel(age_output);


n_real = ...
    opts.n_realizations;


% Preallocate ensemble matrices

SYN = ...
    struct();


SYN.thir_uniform = ...
    nan( ...
    n_output, ...
    n_real, ...
    "single");


SYN.thir_epica_resolution = ...
    nan( ...
    n_output, ...
    n_real, ...
    "single");


SYN.hilbert_uniform = ...
    nan( ...
    n_output, ...
    n_real, ...
    "single");


SYN.hilbert_epica_resolution = ...
    nan( ...
    n_output, ...
    n_real, ...
    "single");


% Adaptive burn-in

adaptive_burn_in = ...
    ceil( ...
    20 ...
    / max( ...
    1 - abs(EPICA.phi), ...
    1e-4));


burn_in = ...
    max( ...
    opts.burn_in_steps, ...
    adaptive_burn_in);


fprintf( ...
    "\nRunning %d stationary AR(1) realisations...\n", ...
    n_real);




% 8. MONTE CARLO LOOP


for first_realisation = ...
        1 : ...
        opts.chunk_size : ...
        n_real


    last_realisation = ...
        min( ...
        first_realisation ...
        + opts.chunk_size ...
        - 1, ...
        n_real);


    column_index = ...
        first_realisation : ...
        last_realisation;


    n_chunk = ...
        numel( ...
        column_index);


    fprintf( ...
        "  %d--%d of %d\n", ...
        first_realisation, ...
        last_realisation, ...
        n_real);


    
    % Generate Gaussian innovations for an approximately
    % unit-variance stationary AR(1) process
    
    innovations = ...
        sqrt( ...
        1 - EPICA.phi^2) ...
        .* randn( ...
        numel(age) ...
        + burn_in, ...
        n_chunk);


   
    % Generate raw AR(1) realisations
  

    synthetic_raw = ...
        filter( ...
        1, ...
        [1 -EPICA.phi], ...
        innovations, ...
        [], ...
        1);


    % Remove burn-in

    synthetic_raw = ...
        synthetic_raw( ...
        burn_in + 1 : end, ...
        :);


    
    % Standardise each realisation and scale it to the
    % standard deviation of the detrended EPICA record
  

    synthetic_standardised = ...
        zscore_columns( ...
        synthetic_raw);


    synthetic_uniform = ...
        EPICA.sigma_residual ...
        .* synthetic_standardised;


    
    % Apply the original EPICA sampling structure
   

    synthetic_at_observations = ...
        interp1( ...
        age, ...
        synthetic_uniform, ...
        age_obs, ...
        opts.interp_method);


    synthetic_epica_resolution = ...
        interp1( ...
        age_obs, ...
        synthetic_at_observations, ...
        age, ...
        opts.interp_method);


   
    % Thirumalai-style mMCV
    

    [~, thir_uniform] = ...
        filtered_moving_std_with_padding( ...
        synthetic_uniform, ...
        b_hp10, ...
        a_hp10, ...
        npad, ...
        half_window_points);


    [~, thir_epica_resolution] = ...
        filtered_moving_std_with_padding( ...
        synthetic_epica_resolution, ...
        b_hp10, ...
        a_hp10, ...
        npad, ...
        half_window_points);


    
    % Thesis Hilbert-amplitude mMCV
    

    [~, hilbert_uniform] = ...
        filtered_hilbert_with_padding( ...
        synthetic_uniform, ...
        b_bp2_10, ...
        a_bp2_10, ...
        npad);


    [~, hilbert_epica_resolution] = ...
        filtered_hilbert_with_padding( ...
        synthetic_epica_resolution, ...
        b_bp2_10, ...
        a_bp2_10, ...
        npad);


    hilbert_uniform = ...
        zscore_columns( ...
        hilbert_uniform);


    hilbert_epica_resolution = ...
        zscore_columns( ...
        hilbert_epica_resolution);

    thir_uniform = ...
        thir_uniform( ...
        output_index, ...
        :);


    thir_epica_resolution = ...
        thir_epica_resolution( ...
        output_index, ...
        :);


    hilbert_uniform = ...
        hilbert_uniform( ...
        output_index, ...
        :);


    hilbert_epica_resolution = ...
        hilbert_epica_resolution( ...
        output_index, ...
        :);

    SYN.thir_uniform( ...
        :, ...
        column_index) = ...
        single( ...
        gaussian_smooth_matrix( ...
        thir_uniform, ...
        opts.output_dt_kyr, ...
        opts.gaussian_window_kyr));


    SYN.thir_epica_resolution( ...
        :, ...
        column_index) = ...
        single( ...
        gaussian_smooth_matrix( ...
        thir_epica_resolution, ...
        opts.output_dt_kyr, ...
        opts.gaussian_window_kyr));


    SYN.hilbert_uniform( ...
        :, ...
        column_index) = ...
        single( ...
        gaussian_smooth_matrix( ...
        hilbert_uniform, ...
        opts.output_dt_kyr, ...
        opts.gaussian_window_kyr));


    SYN.hilbert_epica_resolution( ...
        :, ...
        column_index) = ...
        single( ...
        gaussian_smooth_matrix( ...
        hilbert_epica_resolution, ...
        opts.output_dt_kyr, ...
        opts.gaussian_window_kyr));


end


fprintf( ...
    "Monte Carlo simulations completed.\n");




% 9. CALCULATE ENSEMBLE SUMMARIES
SUMMARY = ...
    struct();


SUMMARY.thir_uniform = ...
    ensemble_summary( ...
    SYN.thir_uniform, ...
    opts.percentiles);


SUMMARY.thir_epica_resolution = ...
    ensemble_summary( ...
    SYN.thir_epica_resolution, ...
    opts.percentiles);


SUMMARY.hilbert_uniform = ...
    ensemble_summary( ...
    SYN.hilbert_uniform, ...
    opts.percentiles);


SUMMARY.hilbert_epica_resolution = ...
    ensemble_summary( ...
    SYN.hilbert_epica_resolution, ...
    opts.percentiles);




% 10. CREATE COMPACT SIX-PANEL FIGURE


fig = ...
    figure( ...
    "Color", ...
    "w", ...
    "Units", ...
    "centimeters", ...
    "Position", ...
    opts.figure_position, ...
    "Renderer", ...
    "painters");


ax = ...
    create_six_panel_axes( ...
    fig);


% Colours

raw_colour = ...
    [0.72 0.72 0.72];


smooth_colour = ...
    [0.75 0.10 0.10];


lt2_colour = ...
    [0.10 0.30 0.75];


band_colour = ...
    [0.85 0.35 0.10];


control_colour = ...
    [0.25 0.45 0.75];


epica_resolution_colour = ...
    [0.80 0.25 0.25];




% PANEL (a): ORIGINAL TEMPORAL RESOLUTION


hold( ...
    ax(1), ...
    "on");


h_spacing = ...
    plot( ...
    ax(1), ...
    age, ...
    1000 ...
    .* EPICA.sampling_interval, ...
    "Color", ...
    raw_colour, ...
    "LineWidth", ...
    0.40);


h_resolution_smooth = ...
    plot( ...
    ax(1), ...
    age, ...
    1000 ...
    .* EPICA.sampling_interval_smooth, ...
    "Color", ...
    [0.20 0.20 0.20], ...
    "LineWidth", ...
    1.15);


ylabel( ...
    ax(1), ...
    "\Delta age (yr)", ...
    "Interpreter", ...
    "tex");


add_panel_heading( ...
    ax(1), ...
    "a", ...
    "Original EPICA temporal resolution", ...
    opts);


legend( ...
    ax(1), ...
    [ ...
    h_spacing ...
    h_resolution_smooth ...
    ], ...
    { ...
    "Observation spacing" ...
    "20-kyr Gaussian smooth" ...
    }, ...
    "Location", ...
    "northeast", ...
    "Box", ...
    "off", ...
    "FontName", ...
    opts.font_name, ...
    "FontSize", ...
    opts.legend_font_size);




% PANEL (b): THIRUMALAI-STYLE mMCV


hold( ...
    ax(2), ...
    "on");


h_thir = ...
    plot( ...
    ax(2), ...
    age, ...
    EPICA.mmcv_thirumalai, ...
    "Color", ...
    raw_colour, ...
    "LineWidth", ...
    0.40);


h_thir_smooth = ...
    plot( ...
    ax(2), ...
    age, ...
    EPICA.mmcv_thirumalai_smooth, ...
    "Color", ...
    smooth_colour, ...
    "LineWidth", ...
    1.25);


ylabel( ...
    ax(2), ...
    "mMCV (‰)");


add_panel_heading( ...
    ax(2), ...
    "b", ...
    "<10 kyr signal: centred 2-kyr rolling SD", ...
    opts);


legend( ...
    ax(2), ...
    [ ...
    h_thir ...
    h_thir_smooth ...
    ], ...
    { ...
    "Thirumalai-style mMCV" ...
    "100-kyr Gaussian smooth" ...
    }, ...
    "Location", ...
    "northeast", ...
    "Box", ...
    "off", ...
    "FontName", ...
    opts.font_name, ...
    "FontSize", ...
    opts.legend_font_size);




% PANEL (c): FREQUENCY DECOMPOSITION


hold( ...
    ax(3), ...
    "on");


h_lt2 = ...
    plot( ...
    ax(3), ...
    age, ...
    EPICA.mmcv_lt2_smooth, ...
    "Color", ...
    lt2_colour, ...
    "LineWidth", ...
    1.20);


h_2_10 = ...
    plot( ...
    ax(3), ...
    age, ...
    EPICA.mmcv_2_10_movstd_smooth, ...
    "Color", ...
    band_colour, ...
    "LineWidth", ...
    1.20);


ylabel( ...
    ax(3), ...
    "mMCV (‰)");


add_panel_heading( ...
    ax(3), ...
    "c", ...
    "Frequency decomposition of the rolling-SD metric", ...
    opts);


legend( ...
    ax(3), ...
    [ ...
    h_lt2 ...
    h_2_10 ...
    ], ...
    { ...
    "<2 kyr" ...
    "2–10 kyr" ...
    }, ...
    "Location", ...
    "northeast", ...
    "Box", ...
    "off", ...
    "FontName", ...
    opts.font_name, ...
    "FontSize", ...
    opts.legend_font_size);




% PANEL (d): HILBERT-AMPLITUDE mMCV


hold( ...
    ax(4), ...
    "on");


h_hilbert = ...
    plot( ...
    ax(4), ...
    age, ...
    EPICA.mmcv_hilbert_z, ...
    "Color", ...
    raw_colour, ...
    "LineWidth", ...
    0.40);


h_hilbert_smooth = ...
    plot( ...
    ax(4), ...
    age, ...
    EPICA.mmcv_hilbert_z_smooth, ...
    "Color", ...
    smooth_colour, ...
    "LineWidth", ...
    1.25);


ylabel( ...
    ax(4), ...
    "mMCV (z-score)");


add_panel_heading( ...
    ax(4), ...
    "d", ...
    "2–10 kyr Hilbert-amplitude mMCV", ...
    opts);


legend( ...
    ax(4), ...
    [ ...
    h_hilbert ...
    h_hilbert_smooth ...
    ], ...
    { ...
    "Hilbert amplitude" ...
    "100-kyr Gaussian smooth" ...
    }, ...
    "Location", ...
    "northeast", ...
    "Box", ...
    "off", ...
    "FontName", ...
    opts.font_name, ...
    "FontSize", ...
    opts.legend_font_size);




% PANEL (e): SYNTHETIC THIRUMALAI RESOLUTION TEST


hold( ...
    ax(5), ...
    "on");


plot_percentile_band( ...
    ax(5), ...
    age_output, ...
    SUMMARY.thir_uniform.p05, ...
    SUMMARY.thir_uniform.p95, ...
    control_colour, ...
    0.18);


plot_percentile_band( ...
    ax(5), ...
    age_output, ...
    SUMMARY.thir_epica_resolution.p05, ...
    SUMMARY.thir_epica_resolution.p95, ...
    epica_resolution_colour, ...
    0.18);


h_control = ...
    plot( ...
    ax(5), ...
    age_output, ...
    SUMMARY.thir_uniform.mean, ...
    "Color", ...
    control_colour, ...
    "LineWidth", ...
    1.25);


h_epica_resolution = ...
    plot( ...
    ax(5), ...
    age_output, ...
    SUMMARY.thir_epica_resolution.mean, ...
    "Color", ...
    epica_resolution_colour, ...
    "LineWidth", ...
    1.25);


ylabel( ...
    ax(5), ...
    "mMCV (‰)");


add_panel_heading( ...
    ax(5), ...
    "e", ...
    "Synthetic resolution test: Thirumalai-style metric", ...
    opts);


legend( ...
    ax(5), ...
    [ ...
    h_control ...
    h_epica_resolution ...
    ], ...
    { ...
    "Uniform control" ...
    "EPICA resolution" ...
    }, ...
    "Location", ...
    "northeast", ...
    "Box", ...
    "off", ...
    "FontName", ...
    opts.font_name, ...
    "FontSize", ...
    opts.legend_font_size);




% PANEL (f): SYNTHETIC HILBERT RESOLUTION TEST


hold( ...
    ax(6), ...
    "on");


plot_percentile_band( ...
    ax(6), ...
    age_output, ...
    SUMMARY.hilbert_uniform.p05, ...
    SUMMARY.hilbert_uniform.p95, ...
    control_colour, ...
    0.18);


plot_percentile_band( ...
    ax(6), ...
    age_output, ...
    SUMMARY.hilbert_epica_resolution.p05, ...
    SUMMARY.hilbert_epica_resolution.p95, ...
    epica_resolution_colour, ...
    0.18);


plot( ...
    ax(6), ...
    age_output, ...
    SUMMARY.hilbert_uniform.mean, ...
    "Color", ...
    control_colour, ...
    "LineWidth", ...
    1.25);


plot( ...
    ax(6), ...
    age_output, ...
    SUMMARY.hilbert_epica_resolution.mean, ...
    "Color", ...
    epica_resolution_colour, ...
    "LineWidth", ...
    1.25);


ylabel( ...
    ax(6), ...
    "mMCV (z-score)");


xlabel( ...
    ax(6), ...
    "Age (kyr BP)", ...
    "FontName", ...
    opts.font_name, ...
    "FontSize", ...
    opts.xlabel_font_size);


add_panel_heading( ...
    ax(6), ...
    "f", ...
    "Synthetic resolution test: Hilbert-amplitude metric", ...
    opts);




% 11. APPLY COMMON AXIS FORMATTING


for i = ...
        1 : ...
        numel(ax)


    xlim( ...
        ax(i), ...
        [ ...
        age(1) ...
        age(end) ...
        ]);


    xticks( ...
        ax(i), ...
        0 : 100 : 800);


    style_axis( ...
        ax(i), ...
        opts);

    % Hide the lowest and highest y-axis tick labels,
    % while retaining the tick marks and grid lines

    y_tick_labels = ...
        string( ...
        ax(i).YTickLabel);

    if numel(y_tick_labels) >= 2

        y_tick_labels(1) = "";
        y_tick_labels(end) = "";

        ax(i).YTickLabel = ...
            y_tick_labels;

    end
    % Hide x-axis labels on the upper five panels

    if ...
            i < numel(ax)

        ax(i).XTickLabel = ...
            [];

    end


end


linkaxes( ...
    ax, ...
    "x");


% Force all available text objects to use Cambria Math

set( ...
    findall( ...
    fig, ...
    "-property", ...
    "FontName"), ...
    "FontName", ...
    opts.font_name);


drawnow;




% 12. EXPORT


if ...
        opts.export_figure


    % Vector PDF

    exportgraphics( ...
        fig, ...
        opts.output_name ...
        + ".pdf", ...
        "ContentType", ...
        "vector", ...
        "BackgroundColor", ...
        "white");


    % Vector SVG for Overleaf

    print( ...
        fig, ...
        opts.output_name ...
        + ".svg", ...
        "-dsvg");


    fprintf( ...
        "\nFigure exported as:\n");


    fprintf( ...
        "  %s.pdf\n", ...
        opts.output_name);


    fprintf( ...
        "  %s.svg\n", ...
        opts.output_name);


end


fprintf( ...
    "\nAnalysis completed.\n");




% LOCAL FUNCTIONS




function ...
    [age, proxy] = ...
    read_epica_record( ...
    filename, ...
    age_min, ...
    age_max)


    if ...
            ~isfile(filename)

        error( ...
            "EPICA file not found: %s", ...
            filename);

    end


    M = ...
        readmatrix( ...
        filename);


    if ...
            size(M, 2) ...
            < 2

        error( ...
            [ ...
            "%s must contain age and proxy values " ...
            "in its first two columns." ...
            ], ...
            filename);

    end


    age = ...
        M(:, 1);


    proxy = ...
        M(:, 2);


    valid = ...
        isfinite(age) & ...
        isfinite(proxy);


    age = ...
        age(valid);


    proxy = ...
        proxy(valid);


    % Convert years to kyr if necessary

    if ...
            max(age) ...
            > 5000

        age = ...
            age ...
            / 1000;

    end


    [age, order] = ...
        sort( ...
        age, ...
        "ascend");


    proxy = ...
        proxy(order);


    [age, unique_index] = ...
        unique( ...
        age, ...
        "stable");


    proxy = ...
        proxy(unique_index);


    keep = ...
        age >= age_min & ...
        age <= age_max;


    age = ...
        age(keep);


    proxy = ...
        proxy(keep);


    if ...
            numel(age) ...
            < 100

        error( ...
            "Too few EPICA observations remain.");

    end


end



function ...
    [filtered_signal, moving_sigma] = ...
    filtered_moving_std_with_padding( ...
    y, ...
    b, ...
    a, ...
    npad, ...
    half_window)


    y = ...
        ensure_column_matrix( ...
        y);


    y_pad = ...
        mirror_pad_matrix( ...
        y, ...
        npad);


    filtered_pad = ...
        filtfilt( ...
        b, ...
        a, ...
        y_pad);


    moving_sigma_pad = ...
        movstd( ...
        filtered_pad, ...
        [ ...
        half_window ...
        half_window ...
        ], ...
        0, ...
        1, ...
        "omitnan", ...
        "Endpoints", ...
        "shrink");


    n = ...
        size( ...
        y, ...
        1);


    filtered_signal = ...
        filtered_pad( ...
        npad + 1 : ...
        npad + n, ...
        :);


    moving_sigma = ...
        moving_sigma_pad( ...
        npad + 1 : ...
        npad + n, ...
        :);


end



function ...
    [filtered_signal, amplitude] = ...
    filtered_hilbert_with_padding( ...
    y, ...
    b, ...
    a, ...
    npad)


    y = ...
        ensure_column_matrix( ...
        y);


    y_pad = ...
        mirror_pad_matrix( ...
        y, ...
        npad);


    filtered_pad = ...
        filtfilt( ...
        b, ...
        a, ...
        y_pad);


    amplitude_pad = ...
        abs( ...
        hilbert( ...
        filtered_pad));


    n = ...
        size( ...
        y, ...
        1);


    filtered_signal = ...
        filtered_pad( ...
        npad + 1 : ...
        npad + n, ...
        :);


    amplitude = ...
        amplitude_pad( ...
        npad + 1 : ...
        npad + n, ...
        :);


end



function ...
    y_pad = ...
    mirror_pad_matrix( ...
    y, ...
    npad)


    y = ...
        ensure_column_matrix( ...
        y);


    n = ...
        size( ...
        y, ...
        1);


    if ...
            npad >= n

        error( ...
            "Mirror padding must be shorter than the time series.");

    end


    left_pad = ...
        y( ...
        npad + 1 : ...
        -1 : ...
        2, ...
        :);


    right_pad = ...
        y( ...
        n - 1 : ...
        -1 : ...
        n - npad, ...
        :);


    y_pad = ...
        [ ...
        left_pad
        y
        right_pad
        ];


end



function ...
    y_smooth = ...
    gaussian_smooth_matrix( ...
    y, ...
    dt, ...
    window_kyr)


    y = ...
        ensure_column_matrix( ...
        y);


    window_points = ...
        round( ...
        window_kyr ...
        / dt);


    if ...
            mod( ...
            window_points, ...
            2) ...
            == 0

        window_points = ...
            window_points ...
            + 1;

    end


    half_window = ...
        floor( ...
        window_points ...
        / 2);


    x = ...
        ( ...
        -half_window : ...
        half_window ...
        )';


    sigma_points = ...
        window_points ...
        / 6;


    kernel = ...
        exp( ...
        -0.5 ...
        .* ...
        ( ...
        x ...
        ./ sigma_points ...
        ).^2);


    kernel = ...
        kernel ...
        ./ sum(kernel);


    valid = ...
        isfinite(y);


    y0 = ...
        y;


    y0(~valid) = ...
        0;


    numerator = ...
        conv2( ...
        y0, ...
        kernel, ...
        "same");


    denominator = ...
        conv2( ...
        double(valid), ...
        kernel, ...
        "same");


    y_smooth = ...
        numerator ...
        ./ denominator;


    y_smooth( ...
        denominator ...
        == 0) = ...
        NaN;


end



function ...
    z = ...
    zscore_columns( ...
    x)


    x = ...
        ensure_column_matrix( ...
        x);


    mu = ...
        mean( ...
        x, ...
        1, ...
        "omitnan");


    sigma = ...
        std( ...
        x, ...
        0, ...
        1, ...
        "omitnan");


    sigma( ...
        ~isfinite(sigma) ...
        | sigma == 0) = ...
        1;


    z = ...
        ( ...
        x ...
        - mu ...
        ) ...
        ./ sigma;


end



function ...
    x = ...
    ensure_column_matrix( ...
    x)


    if ...
            isvector(x)

        x = ...
            x(:);

    end


end



function ...
    S = ...
    ensemble_summary( ...
    curves, ...
    percentiles)


    curves = ...
        double( ...
        curves);


    Q = ...
        prctile( ...
        curves, ...
        percentiles, ...
        2);


    S.p05 = ...
        Q( ...
        :, ...
        percentiles == 5);


    S.p95 = ...
        Q( ...
        :, ...
        percentiles == 95);


    % Ensemble mean at every time step

    S.mean = ...
        mean( ...
        curves, ...
        2, ...
        "omitnan");


end



function ...
    h = ...
    plot_percentile_band( ...
    ax, ...
    x, ...
    lower, ...
    upper, ...
    colour, ...
    alpha_value)


    h = ...
        fill( ...
        ax, ...
        [ ...
        x(:)
        flipud(x(:))
        ], ...
        [ ...
        lower(:)
        flipud(upper(:))
        ], ...
        colour, ...
        "FaceAlpha", ...
        alpha_value, ...
        "EdgeColor", ...
        "none", ...
        "HandleVisibility", ...
        "off");


end



function ...
    ax = ...
    create_six_panel_axes( ...
    fig)


   
    % Manual layout provides thinner and more tightly stacked
    % panels than tiledlayout.
    
    n_panels = ...
        6;


  left_margin = 0.18;
  axis_width  = 0.64;
  right_margin = 1 - left_margin - axis_width;

    top_margin = ...
        0.025;


    bottom_margin = ...
        0.070;


    % Small gaps between related panels

    standard_gap = ...
        0.006;


    % Slightly larger separation between the real-data and
    % synthetic-experiment sections

    group_gap = ...
        0.022;


    gap_after = ...
        [ ...
        standard_gap
        standard_gap
        standard_gap
        group_gap
        standard_gap
        ];


    axis_width = ...
        1 ...
        - left_margin ...
        - right_margin;


    total_gap = ...
        sum( ...
        gap_after);


    axis_height = ...
        ( ...
        1 ...
        - top_margin ...
        - bottom_margin ...
        - total_gap ...
        ) ...
        / n_panels;


    ax = ...
        gobjects( ...
        n_panels, ...
        1);


    current_top = ...
        1 ...
        - top_margin;


    for i = ...
            1 : ...
            n_panels


        axis_bottom = ...
            current_top ...
            - axis_height;


        ax(i) = ...
            axes( ...
            "Parent", ...
            fig, ...
            "Position", ...
            [ ...
            left_margin ...
            axis_bottom ...
            axis_width ...
            axis_height ...
            ]);


        current_top = ...
            axis_bottom;


        if ...
                i < n_panels

            current_top = ...
                current_top ...
                - gap_after(i);

        end


    end


end



function style_axis(ax, opts)

    set( ...
        ax, ...
        "FontName", opts.font_name, ...
        "FontSize", opts.axis_font_size, ...
        "LineWidth", 0.55, ...
        "TickDir", "out", ...
        "Box", "off", ...
        "Layer", "bottom", ...
        "Color", [0.975 0.935 0.945], ...
        "XColor", [0.32 0.32 0.32], ...
        "YColor", [0.32 0.32 0.32], ...
        "XGrid", "on", ...
        "YGrid", "on", ...
        "GridColor", [1 1 1], ...
        "GridAlpha", 0.9, ...
        "GridLineStyle", "-", ...
        "XMinorGrid", "on", ...
        "YMinorGrid", "on", ...
        "MinorGridColor", [1 1 1], ...
        "MinorGridAlpha", 0.5);

    ax.YLabel.FontName = opts.font_name;
    ax.YLabel.FontSize = opts.ylabel_font_size;

end



function add_panel_heading(ax, letter, heading, opts)

    
    % Panel letter outside the plotting area
    
    text( ...
        ax, ...
        -0.055, ...
        0.87, ...
        sprintf("(%s)", letter), ...
        "Units", ...
        "normalized", ...
        "FontName", ...
        opts.font_name, ...
        "FontSize", ...
        opts.panel_heading_font_size, ...
        "FontWeight", ...
        "bold", ...
        "Color", ...
        [0.15 0.15 0.15], ...
        "HorizontalAlignment", ...
        "right", ...
        "VerticalAlignment", ...
        "top", ...
        "Clipping", ...
        "off");


    
    % Panel title inside the plotting area
   

    text( ...
        ax, ...
        0.018, ...
        0.92, ...
        heading, ...
        "Units", ...
        "normalized", ...
        "FontName", ...
        opts.font_name, ...
        "FontSize", ...
        opts.panel_heading_font_size, ...
        "FontWeight", ...
        "bold", ...
        "Color", ...
        [0.15 0.15 0.15], ...
        "HorizontalAlignment", ...
        "left", ...
        "VerticalAlignment", ...
        "top", ...
        "Clipping", ...
        "on");

end