
% Synthetic mMCV test: trend-geometry sensitivity

% Fixed synthetic settings:
%   age range          = 0-800 kyr BP
%   true transition    = 600 kyr BP
%   temporal spacing   = 0.5 kyr
%   signal:noise       = 1:0.2
%   proxy AR(1) phi    = 0.93004
%
% Methods:
%   1. Original Abram / Marron SiZer via chpttests.m
%   2. MATLAB findchangepts via chpttests.m
%   3. BEAST
%


clear;
close all;
clc;

rng(1); 


% 1. SYNTHETIC DATA SETTINGS
dt = 0.5;                     % kyr
age_max = 800;                % kyr BP
age = (0:dt:age_max)';        % ascending 0 -> 800
n = numel(age);
change_age = 600;             % prescribed transition age, kyr BP

% Proxy-derived parameters
sigma_proxy = 0.88047;
phi_proxy = 0.93004;

% Total imposed signal change
deltaT = 2 * sigma_proxy;

% Weak-noise experiment:
% DeltaT : 2*sigma_noise = 1 : 0.2
noise_ratio = 0.2;
sigma_noise = noise_ratio * deltaT / 2;

burnin = 2000;
nRep = 10;



% 2. SHARED SIZER AND FINDCHANGEPTS SETTINGS


if exist('chpttests', 'file') ~= 2
    error(['chpttests.m was not found on the MATLAB path. ' ...
           'Place it beside this script or add its folder to the path.']);
end

opts = struct();

opts.methods = ...
    [ ...
    "sizer" ...
    "findchangepts" ...
    ];


% SiZer: final Abram / Marron setup

opts.sizer.bandwidth_min = 60;
opts.sizer.bandwidth_max = 100;
opts.sizer.n_bandwidths = 41;
opts.sizer.x_step = 1.0;
opts.sizer.alpha = 0.10;
opts.sizer.simflag = 2;
opts.sizer.iregtdist = 0;
opts.sizer.endpoint_flag = 0;
opts.sizer.boundary_adjustment = 0;

opts.sizer.onset_mode = "all";
opts.sizer.min_run_kyr = 40;
opts.sizer.edge_ignore_kyr = 0;
opts.sizer.cluster_gap_kyr = 35;
opts.sizer.min_bw_fraction = 0.80;
opts.sizer.uncertainty_mode = "iqr";

%% ------------------------------------------------------------
% findchangepts
%% ------------------------------------------------------------

opts.findchangepts.smooth_kyr = 0;
opts.findchangepts.max_num_changes = 1;

%% ============================================================
% 3. BEAST SETTINGS
%% ============================================================

if exist('beast', 'file') ~= 2
    error(['The BEAST function was not found on the MATLAB path. ' ...
           'Add the BEAST folder before running this script.']);
end

beast_tcp_minmax = [0 1];
beast_torder_minmax = [0 1];

beast_mcmc_samples = 4000;
beast_mcmc_burnin = 1000;
beast_mcmc_chains = 2;
beast_mcmc_thin = 5;

%% ============================================================
% 4. BUILD SIX CLEAN TREND GEOMETRIES
%% ============================================================

trend_names = {
    'Flat'
    'Abrupt jump'
    'Flat to linear increase'
    'Flat to curved increase'
    'Linear decrease to increase'
    'Curved decrease to increase'
    };

roman_labels = {'i','ii','iii','iv','v','vi'};

nTrend = numel(trend_names);
clean_trend = zeros(n, nTrend);

older = age >= change_age;
younger = age <= change_age;

% Younger-side coordinate:
% u = 0 at 600 kyr BP
% u = 1 at the present
u_young = (change_age - age(younger)) / change_age;

% Older-side coordinate:
% v = 0 at 600 kyr BP
% v = 1 at 800 kyr BP
v_old = (age(older) - change_age) / (age_max - change_age);

% i) Flat
clean_trend(:,1) = 0;

% ii) Abrupt jump at 600 kyr BP
tmp = zeros(n,1);
tmp(younger) = deltaT;
clean_trend(:,2) = tmp;

% iii) Flat, then linear increase towards the present
tmp = zeros(n,1);
tmp(younger) = deltaT * u_young;
clean_trend(:,3) = tmp;

% iv) Flat, then curved accelerating increase towards the present
tmp = zeros(n,1);
tmp(younger) = deltaT * ...
    (1 - cos((pi/2) * u_young));
clean_trend(:,4) = tmp;

% v) Linear decrease to 600 kyr BP, then linear increase
tmp = zeros(n,1);
tmp(older) = deltaT * v_old;
tmp(younger) = deltaT * u_young;
clean_trend(:,5) = tmp;

% vi) Curved decrease to 600 kyr BP, then curved increase
tmp = zeros(n,1);
tmp(older) = deltaT * ...
    (1 - cos((pi/2) * v_old));
tmp(younger) = deltaT * ...
    (1 - cos((pi/2) * u_young));
clean_trend(:,6) = tmp;

%% ============================================================
% 5. GENERATE THE SAME 100 NOISE REALISATIONS FOR ALL TRENDS
%% ============================================================

noise_all = nan(n, nRep);

for r = 1:nRep

    noise_long = zeros(n + burnin, 1);

    for k = 2:(n + burnin)
        noise_long(k) = ...
            phi_proxy * noise_long(k-1) + randn;
    end

    noise_raw = noise_long(burnin+1:end);

    noise_standardised = ...
        (noise_raw - mean(noise_raw, 'omitnan')) ./ ...
        std(noise_raw, 'omitnan');

    noise_all(:,r) = ...
        sigma_noise * noise_standardised;

end


% 6. OUTPUT STORAGE


cp_sizer = nan(nRep, nTrend);
cp_findchangepts = nan(nRep, nTrend);
cp_beast = nan(nRep, nTrend);

sizer_success = false(nRep, nTrend);
findcp_success = false(nRep, nTrend);
beast_success = false(nRep, nTrend);

beast_ncp_mode = nan(nRep, nTrend);

% Store the first noisy realisation for the left-hand panels
example_series = nan(n, nTrend);


% 7. MONTE CARLO LOOP


fprintf('\n============================================================\n');
fprintf('TREND-GEOMETRY MONTE CARLO TEST\n');
fprintf('============================================================\n');
fprintf('Realisations per trend: %d\n', nRep);
fprintf('Signal:noise = 1:%.1f\n', noise_ratio);
fprintf('Noise sigma = %.6f\n', sigma_noise);
fprintf('Proxy AR(1) phi = %.6f\n', phi_proxy);
fprintf('True transition age = %.1f kyr BP\n', change_age);
fprintf('============================================================\n\n');

for j = 1:nTrend

    fprintf('Trend %d/%d: %s\n', ...
        j, nTrend, trend_names{j});

    for r = 1:nRep

        
        % Synthetic proxy
        

        synthetic_raw = ...
            clean_trend(:,j) + noise_all(:,r);

        synthetic_z = ...
            (synthetic_raw - mean(synthetic_raw, 'omitnan')) ./ ...
            std(synthetic_raw, 'omitnan');

        if r == 1
            example_series(:,j) = synthetic_raw;
        end

        
        % 1-2. SIZER AND FINDCHANGEPTS VIA CHPTTESTS
        

        try

            out = ...
                chpttests( ...
                age, ...
                synthetic_z, ...
                opts);

            cp_sizer(r,j) = ...
                out.sizer.cp_age;

            cp_findchangepts(r,j) = ...
                out.findchangepts.cp_age;

            sizer_success(r,j) = ...
                out.sizer.run_successful;

            findcp_success(r,j) = ...
                out.findchangepts.run_successful;

        catch ME

            if r == 1
                fprintf( ...
                    '  SiZer/findchangepts error: %s\n', ...
                    ME.message);
            end

        end

        
        % 3. BEAST
       

        try

            beast_seed = ...
                (j - 1) * nRep + r;

            [ ...
                cp_beast(r,j), ...
                beast_ncp_mode(r,j) ...
                ] = ...
                run_beast_once( ...
                synthetic_z, ...
                age, ...
                dt, ...
                age_max, ...
                beast_tcp_minmax, ...
                beast_torder_minmax, ...
                beast_seed, ...
                beast_mcmc_samples, ...
                beast_mcmc_burnin, ...
                beast_mcmc_chains, ...
                beast_mcmc_thin);

            beast_success(r,j) = true;

        catch ME

            if r == 1
                fprintf('  BEAST error: %s\n', ME.message);
            end

        end

        
        % Progress
       

        if mod(r,10) == 0
            fprintf('  %d / %d complete\n', r, nRep);
        end

    end

end

fprintf('\nAll Monte Carlo calculations completed.\n');


% 8. SUMMARY TABLE

Summary = build_summary_table( ...
    trend_names, ...
    cp_sizer, ...
    cp_findchangepts, ...
    cp_beast, ...
    change_age, ...
    nRep);

disp(' ');
disp('MONTE CARLO SUMMARY');
disp(Summary);


% 9. PRINT BEAST MODEL-SELECTION SUMMARY

fprintf('\nBEAST MODEL-SELECTION SUMMARY\n');
fprintf('-----------------------------------------------\n');

for j = 1:nTrend

    valid = beast_success(:,j) & ...
        isfinite(beast_ncp_mode(:,j));

    n_valid = sum(valid);

    if n_valid == 0

        fprintf('%-32s : no valid BEAST runs\n', ...
            trend_names{j});

    else

        pct_0 = 100 * ...
            sum(beast_ncp_mode(valid,j) == 0) / ...
            n_valid;

        pct_1 = 100 * ...
            sum(beast_ncp_mode(valid,j) >= 1) / ...
            n_valid;

        fprintf( ...
            '%-32s : 0 CP = %5.1f%%; 1 CP = %5.1f%%\n', ...
            trend_names{j}, ...
            pct_0, ...
            pct_1);

    end

end


% 10. FIGURE SETTINGS


font_name = 'Cambria Math';

col_sizer = [0.05 0.15 0.95];
col_find = [1.00 0.45 0.00];
col_beast = [0.72 0.00 0.88];

% Common relative-error limit for all three method columns
all_error = [
    cp_sizer(:) - change_age
    cp_findchangepts(:) - change_age
    cp_beast(:) - change_age
    ];

all_error = all_error(isfinite(all_error));

if isempty(all_error)

    error_limit = 100;

else

    q95_abs = local_percentile( ...
        abs(all_error), ...
        95);

    error_limit = ...
        max(50, 25 * ceil(q95_abs / 25));

end

% Leave a little room but avoid a needlessly huge axis
error_limit = min(max(error_limit, 50), 400);


% 11. CREATE FIGURE

fig = figure( ...
    'Color', ...
    'w', ...
    'Units', ...
    'pixels', ...
    'Position', ...
    [50 40 1250 820], ...
    'Renderer', ...
    'painters');

left_margin = 0.065;
right_margin = 0.025;
top_margin = 0.055;
bottom_margin = 0.070;

row_gap = 0.008;
column_gap = 0.014;

column_widths = [0.40 0.18 0.18 0.18];

usable_width = ...
    1 - left_margin - right_margin - ...
    3 * column_gap;

column_widths = ...
    column_widths / sum(column_widths) * ...
    usable_width;

x0 = nan(1,4);
x0(1) = left_margin;

for c = 2:4
    x0(c) = ...
        x0(c-1) + ...
        column_widths(c-1) + ...
        column_gap;
end

panel_height = ...
    (1 - top_margin - bottom_margin - ...
    (nTrend - 1) * row_gap) / ...
    nTrend;

% Common y limits for example synthetic series
all_example = [
    example_series(:)
    clean_trend(:)
    ];

all_example = ...
    all_example(isfinite(all_example));

y_min = min(all_example);
y_max = max(all_example);

y_pad = 0.06 * (y_max - y_min);

if y_pad == 0
    y_pad = 1;
end

example_ylim = ...
    [y_min - y_pad, y_max + y_pad];


% 12. DRAW THE FOUR-COLUMN FIGURE


for j = 1:nTrend

    y0 = ...
        1 - top_margin - ...
        j * panel_height - ...
        (j - 1) * row_gap;

    
    % Column 1: synthetic example
    

    ax1 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(1), y0, column_widths(1), panel_height]);

    plot( ...
        ax1, ...
        age, ...
        example_series(:,j), ...
        'Color', ...
        [0.65 0.65 0.65], ...
        'LineWidth', ...
        0.55);

    hold(ax1, 'on');

    plot( ...
        ax1, ...
        age, ...
        clean_trend(:,j), ...
        'k-', ...
        'LineWidth', ...
        1.8);

    xline( ...
        ax1, ...
        change_age, ...
        '--', ...
        'Color', ...
        [0.35 0.35 0.35], ...
        'LineWidth', ...
        1.0);

    set( ...
        ax1, ...
        'XDir', ...
        'reverse', ...
        'XLim', ...
        [0 age_max], ...
        'YLim', ...
        example_ylim, ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        18, ...
        'LineWidth', ...
        0.7, ...
        'TickDir', ...
        'out', ...
        'Box', ...
        'on', ...
        'Color', ...
        [0.95 0.92 0.94], ...
        'XGrid', ...
        'on', ...
        'YGrid', ...
        'on', ...
        'GridColor', ...
        [1 1 1], ...
        'GridAlpha', ...
        1.0, ...
        'GridLineStyle', ...
        '-', ...
        'Layer', ...
        'bottom');

    % Keep the two y-axis labels well inside each panel so that
    % labels from adjacent rows do not overlap.
    y_range = ...
        example_ylim(2) - example_ylim(1);

    ax1.YTick = ...
        [ ...
        example_ylim(1) + 0.25 * y_range, ...
        example_ylim(1) + 0.75 * y_range ...
        ];

    ax1.YTickLabel = ...
        compose( ...
        '%.1f', ...
        ax1.YTick);

    ax1.XTick = ...
        [0 200 400 600 800];

    if j == 1

        title( ...
            ax1, ...
            'Synthetic trends', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            18);

    end

    if j < nTrend

        ax1.XTickLabel = [];

    else

        xlabel( ...
            ax1, ...
            'Age BP (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            18);

    end

    % Put the trend-geometry label inside the panel so that it
    % cannot overlap the numerical y-axis tick labels.
    text( ...
        ax1, ...
        0.018, ...
        0.82, ...
        roman_labels{j}, ...
        'Units', ...
        'normalized', ...
        'HorizontalAlignment', ...
        'left', ...
        'VerticalAlignment', ...
        'middle', ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        18, ...
        'FontWeight', ...
        'bold', ...
        'Clipping', ...
        'on');

   
    % Column 2: SiZer
   

    ax2 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(2), y0, column_widths(2), panel_height]);

    draw_detection_distribution( ...
        ax2, ...
        cp_sizer(:,j), ...
        change_age, ...
        nRep, ...
        col_sizer, ...
        error_limit, ...
        font_name);

    if j == 1

        title( ...
            ax2, ...
            'SiZer', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            18);

    end

    if j < nTrend

        ax2.XTickLabel = [];

    else

        xlabel( ...
            ax2, ...
            'Detected age - 600 kyr (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            188);

    end

    
    % Column 3: findchangepts
    
    ax3 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(3), y0, column_widths(3), panel_height]);

    draw_detection_distribution( ...
        ax3, ...
        cp_findchangepts(:,j), ...
        change_age, ...
        nRep, ...
        col_find, ...
        error_limit, ...
        font_name);

    if j == 1

        title( ...
            ax3, ...
            'findchangepts', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            18);

    end

    if j < nTrend

        ax3.XTickLabel = [];

    else

        xlabel( ...
            ax3, ...
            'Detected age - 600 kyr (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            18);

    end

    
    % Column 4: BEAST
    

    ax4 = axes( ...
        'Parent', ...
        fig, ...
        'Position', ...
        [x0(4), y0, column_widths(4), panel_height]);

    draw_detection_distribution( ...
        ax4, ...
        cp_beast(:,j), ...
        change_age, ...
        nRep, ...
        col_beast, ...
        error_limit, ...
        font_name);

    if j == 1

        title( ...
            ax4, ...
            'BEAST', ...
            'FontWeight', ...
            'normal', ...
            'FontSize', ...
            18);

    end

    if j < nTrend

        ax4.XTickLabel = [];

    else

        xlabel( ...
            ax4, ...
            'Detected age - 600 kyr (kyr)', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            18);

    end

end

annotation( ...
    fig, ...
    'textbox', ...
    [0.015 0.965 0.035 0.025], ...
    'String', ...
    'a', ...
    'LineStyle', ...
    'none', ...
    'FontName', ...
    font_name, ...
    'FontSize', ...
    18, ...
    'FontWeight', ...
    'bold');

annotation( ...
    fig, ...
    'textbox', ...
    [0.060 0.960 0.25 0.03], ...
    'String', ...
    'Changepoint tests: trend geometry', ...
    'LineStyle', ...
    'none', ...
    'FontName', ...
    font_name, ...
    'FontSize', ...
    18, ...
    'FontWeight', ...
    'normal');

fprintf('\nFigure created. No files were saved.\n');


% LOCAL FUNCTION:
% RUN BEAST ONCE


function [cp_age, ncp_mode] = ...
    run_beast_once( ...
    y, ...
    age, ...
    dt, ...
    age_max, ...
    tcp_minmax, ...
    torder_minmax, ...
    seed, ...
    mcmc_samples, ...
    mcmc_burnin, ...
    mcmc_chains, ...
    mcmc_thin)

    cp_age = NaN;
    ncp_mode = NaN;

    y = y(:);

    out = beast( ...
        y, ...
        'start', ...
        0, ...
        'deltat', ...
        dt, ...
        'season', ...
        'none', ...
        'tcp.minmax', ...
        tcp_minmax, ...
        'torder.minmax', ...
        torder_minmax, ...
        'mcmc.seed', ...
        seed, ...
        'mcmc.samples', ...
        mcmc_samples, ...
        'mcmc.burnin', ...
        mcmc_burnin, ...
        'mcmc.chains', ...
        mcmc_chains, ...
        'mcmc.thin', ...
        mcmc_thin, ...
        'print.progress', ...
        false, ...
        'print.options', ...
        false);

    if ~isfield(out,'trend')
        return;
    end

    %% Determine posterior modal number of changepoints

    if ...
            isfield(out.trend,'ncp_mode') && ...
            ~isempty(out.trend.ncp_mode)

        tmp = ...
            double(out.trend.ncp_mode(:));

        tmp = ...
            tmp(isfinite(tmp));

        if ~isempty(tmp)
            ncp_mode = tmp(1);
        end

    end

    if ...
            ~isfinite(ncp_mode) && ...
            isfield(out.trend,'ncpPr') && ...
            ~isempty(out.trend.ncpPr)

        ncpPr = ...
            double(out.trend.ncpPr(:));

        [~, idx_mode] = ...
            max(ncpPr);

        ncp_mode = ...
            idx_mode - 1;

    end

    %% Only retain a CP age when the modal model contains one CP

    if ...
            ~isfinite(ncp_mode) || ...
            ncp_mode < 1

        return;

    end

    %% Preferred extraction: reported trend CP candidates

    if ...
            isfield(out.trend,'cp') && ...
            ~isempty(out.trend.cp)

        cp_candidates = ...
            double(out.trend.cp(:));

        if ...
                isfield(out.trend,'cpPr') && ...
                ~isempty(out.trend.cpPr)

            cp_pr = ...
                double(out.trend.cpPr(:));

        else

            cp_pr = ...
                nan(size(cp_candidates));

        end

        valid = ...
            isfinite(cp_candidates) & ...
            cp_candidates >= 0 & ...
            cp_candidates <= age_max;

        if any(valid)

            cp_candidates = ...
                cp_candidates(valid);

            cp_pr = ...
                cp_pr(valid);

            if any(isfinite(cp_pr))

                [~, best] = ...
                    max(cp_pr);

                cp_age = ...
                    cp_candidates(best);

            else

                cp_age = ...
                    cp_candidates(1);

            end

        end

    end

    %% Fallback: maximum CP occurrence probability

    if ...
            ~isfinite(cp_age) && ...
            isfield(out.trend,'cpOccPr') && ...
            ~isempty(out.trend.cpOccPr)

        cp_occ = ...
            double(out.trend.cpOccPr(:));

        if numel(cp_occ) == numel(age)

            [~, best] = ...
                max(cp_occ);

            cp_age = ...
                age(best);

        end

    end

end


% LOCAL FUNCTION:
% BUILD SUMMARY TABLE


function Summary = ...
    build_summary_table( ...
    trend_names, ...
    cp_sizer, ...
    cp_find, ...
    cp_beast, ...
    true_age, ...
    nRep)

    method_names = {
        'SiZer'
        'findchangepts'
        'BEAST'
        };

    method_data = {
        cp_sizer
        cp_find
        cp_beast
        };

    nTrend = numel(trend_names);
    nMethod = numel(method_names);
    nRow = nTrend * nMethod;

    Trend = strings(nRow,1);
    Method = strings(nRow,1);

    Detections = nan(nRow,1);
    DetectionRate_pct = nan(nRow,1);

    MedianAge_kyr = nan(nRow,1);

    Q25_kyr = nan(nRow,1);
    Q75_kyr = nan(nRow,1);

    P05_kyr = nan(nRow,1);
    P95_kyr = nan(nRow,1);

    MedianError_kyr = nan(nRow,1);

    row = 0;

    for j = 1:nTrend

        for m = 1:nMethod

            row = row + 1;

            cp = ...
                method_data{m}(:,j);

            cp = ...
                cp(isfinite(cp));

            Trend(row) = ...
                string(trend_names{j});

            Method(row) = ...
                string(method_names{m});

            Detections(row) = ...
                numel(cp);

            DetectionRate_pct(row) = ...
                100 * numel(cp) / nRep;

            if ~isempty(cp)

                MedianAge_kyr(row) = ...
                    median(cp,'omitnan');

                Q25_kyr(row) = ...
                    local_percentile(cp,25);

                Q75_kyr(row) = ...
                    local_percentile(cp,75);

                P05_kyr(row) = ...
                    local_percentile(cp,5);

                P95_kyr(row) = ...
                    local_percentile(cp,95);

                if j > 1

                    MedianError_kyr(row) = ...
                        median( ...
                        cp - true_age, ...
                        'omitnan');

                end

            end

        end

    end

    Summary = table( ...
        Trend, ...
        Method, ...
        Detections, ...
        DetectionRate_pct, ...
        MedianAge_kyr, ...
        Q25_kyr, ...
        Q75_kyr, ...
        P05_kyr, ...
        P95_kyr, ...
        MedianError_kyr);

end


% LOCAL FUNCTION:
% DRAW ONE METHOD DISTRIBUTION


function draw_detection_distribution( ...
    ax, ...
    cp_age, ...
    true_age, ...
    nRep, ...
    colour, ...
    error_limit, ...
    font_name)

    hold(ax,'on');

    xline( ...
        ax, ...
        0, ...
        '--', ...
        'Color', ...
        [0.35 0.35 0.35], ...
        'LineWidth', ...
        0.9);

    valid = ...
        cp_age(isfinite(cp_age));

    error_age = ...
        valid - true_age;

    if isempty(error_age)

        text( ...
            ax, ...
            0.50, ...
            0.58, ...
            'ND', ...
            'Units', ...
            'normalized', ...
            'HorizontalAlignment', ...
            'center', ...
            'VerticalAlignment', ...
            'middle', ...
            'FontName', ...
            font_name, ...
            'FontSize', ...
            18, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            colour);

    else

        p05 = ...
            local_percentile(error_age,5);

        p95 = ...
            local_percentile(error_age,95);

        q25 = ...
            local_percentile(error_age,25);

        q75 = ...
            local_percentile(error_age,75);

        med = ...
            median(error_age,'omitnan');

        % 5-95% range
        plot( ...
            ax, ...
            [p05 p95], ...
            [0.56 0.56], ...
            '-', ...
            'Color', ...
            colour, ...
            'LineWidth', ...
            1.0);

        % 25-75% range
        plot( ...
            ax, ...
            [q25 q75], ...
            [0.56 0.56], ...
            '-', ...
            'Color', ...
            colour, ...
            'LineWidth', ...
            3.0);

        % Median
        plot( ...
            ax, ...
            med, ...
            0.56, ...
            's', ...
            'MarkerSize', ...
            8, ...
            'MarkerFaceColor', ...
            'w', ...
            'MarkerEdgeColor', ...
            colour, ...
            'LineWidth', ...
            1.5);

    end

    detection_rate = ...
        100 * numel(valid) / nRep;

    text( ...
        ax, ...
        0.50, ...
        0.18, ...
        sprintf( ...
        'Detected: %d/%d (%.0f%%)', ...
        numel(valid), ...
        nRep, ...
        detection_rate), ...
        'Units', ...
        'normalized', ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'middle', ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        18, ...
        'Color', ...
        [0.25 0.25 0.25]);

    set( ...
        ax, ...
        'XLim', ...
        [-1.15 * error_limit, 1.15 * error_limit], ...
        'YLim', ...
        [0 1], ...
        'YTick', ...
        [0.25 0.75], ...
        'YTickLabel', ...
        [], ...
        'FontName', ...
        font_name, ...
        'FontSize', ...
        8, ...
        'LineWidth', ...
        0.7, ...
        'TickDir', ...
        'out', ...
        'TickLength', ...
        [0 0], ...
        'XMinorTick', ...
        'off', ...
        'YMinorTick', ...
        'off', ...
        'Box', ...
        'on', ...
        'Color', ...
        [0.90 0.94 0.99], ...
        'XGrid', ...
        'on', ...
        'YGrid', ...
        'off', ...
        'GridColor', ...
        [0.72 0.72 0.72], ...
        'GridAlpha', ...
        0.3, ...
        'GridLineStyle', ...
        '-', ...
        'Layer', ...
        'bottom');

    % Internal x-axis labels, away from panel boundaries
ax.XTick = ...
    [ ...
    -0.50 * error_limit, ...
     0, ...
     0.50 * error_limit ...
    ];

ax.XTickLabel = ...
    compose( ...
    '%.0f', ...
    ax.XTick);

end


% LOCAL FUNCTION:
% PERCENTILE WITHOUT REQUIRING PRCTILE


function v = ...
    local_percentile( ...
    x, ...
    p)

    x = ...
        sort( ...
        x( ...
        isfinite(x)));

    if isempty(x)

        v = NaN;
        return;

    end

    x = x(:);
    n = numel(x);

    if n == 1

        v = x;
        return;

    end

    position = ...
        1 + ...
        (p / 100) * ...
        (n - 1);

    lo = floor(position);
    hi = ceil(position);

    if lo == hi

        v = x(lo);

    else

        weight = ...
            position - lo;

        v = ...
            (1 - weight) * ...
            x(lo) + ...
            weight * ...
            x(hi);

    end

end
